### ISSUE TITLE
Move image transforms from collate function to the dataset

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#100]
Currently, the collate function converts each image into a pair of transformed images before concatenating them to a batch. This has led to a lot of confusion. Ideally, the transform could be passed to the `LightlyDataset` constructor. 

This would also have an impact on #68. Furthermore, a `LightlyDataset` should have a `train` and `inference` mode to switch between augmentations for contrastive learning and for infering image representations.

**Comment by guarin** [comment]
We refactored augmentations and moved them to transforms.
