### ISSUE TITLE
1.2.40 does not work on Windows

### ISSUE THREAD

**Issue by jfulem** [lightly-ai/lightly#1024]
The new version 1.2.40 is crashing on windows due to `signal.SIGALRM`, which is available only on Unix. Missing attribute on windows.

**Comment by philippmwirth** [comment]
Hi, thanks for reporting the issue! Can you please check if the latest release (`1.2.41`) resolves the problem?

**Comment by jfulem** [comment]
Hi @philippmwirth, I can confirm `1.2.41` works. The problem is resolved. Thanks

**Comment by philippmwirth** [comment]
Thanks for letting me know! 🙂
