### ISSUE TITLE
Issue in Installation

### ISSUE THREAD

**Issue by ptnv-s** [lightly-ai/lightly#1026]
Hi, I am trying to install lightly with the current set of dependencies of a previous project to integrate and implement SSL in paperspace jupyterlab platform. However, the installation is not successful. 

![image](https://user-images.githubusercontent.com/72119231/210487127-8f11d0b3-6bd0-4722-aac6-500b6fae8d54.png)

Python version is 3.8, and the torch is 1.11.0a0+17540c5 based on paperspace/nb-pytorch:22.02-py3 container.

**Comment by guarin** [comment]
Hi @ptnv-s, thanks for reporting the issue.

Is it possible that you have torchvision version 0.11.2 or 0.11.3? I believe there might be an issue how we check if a torchvision version with transformer support is installed (should be at least torchvision 0.12.0).

**Comment by ptnv-s** [comment]
Yes, I was able to resolve it. Basically, there was a dependency error wrt other libraries.
Thanks a lot!
