### ISSUE TITLE
Changing output dimension to 128

### ISSUE THREAD

**Issue by inoejj** [lightly-ai/lightly#1031]
Hi. I am trying out this package and following the Tutorial 3 (https://docs.lightly.ai/self-supervised-learning/tutorials/package/tutorial_simclr_clothing.html)

I thought this snippet of code is enough to set my output tensor to a shape of 128.
`self.projection_head = SimCLRProjectionHead(hidden_dim, hidden_dim, 128)` 

However, when I use your `generate_embeddings` function and print the shape, it shows a shape of 512. I wonder if you can point me to the right direction to set my output dimension to 128 during training a SimClr model.

**Comment by philippmwirth** [comment]
Hi @inoejj, thanks for trying out the tutorial!

The reason is that the embeddings are done with the `backbone` (without the projection head). During training, the output dimension will be `128` because training makes use of the projection head.

**Comment by inoejj** [comment]
Thank you for your prompt reply. 

Let's say I am using the SimClr model from here https://docs.lightly.ai/self-supervised-learning/examples/simclr.html, and I saved the model using `torch.save(model.state_dict(), 'model.ckpt')`, loaded it with 
```
model = SimCLRModel()
model.load_state_dict(torch.load('model.ckpt'))
model.eval()
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
```
What should I do before or after the training if I wished to obtain an output feature shape of 128 as per the SimClr paper?

**Comment by philippmwirth** [comment]
I believe it should be enough to replace the following line in `generate_embeddings`
```python
# emb = model.backbone(img).flatten(start_dim=1)
emb = model(img).flatten(start_dim=1)
```

**Comment by inoejj** [comment]
Awesome! Thank you so much for your help!

**Comment by inoejj** [comment]
If I were to use Swav instead of SimClr and use the `emb = model(img).flatten(start_dim=1)`, it produced an output shape of 512. How can I change that to 128, can you point out my mistake ? Thanks.

```
class SwaV(pl.LightningModule):
    def __init__(self):
        super().__init__()
        resnet = torchvision.models.resnet18()
        self.backbone = nn.Sequential(*list(resnet.children())[:-1])

        hidden_dim = resnet.fc.in_features
        self.projection_head = SwaVProjectionHead(hidden_dim, hidden_dim, 128)
        self.prototypes = SwaVPrototypes(128, n_prototypes=512)
        self.criterion = SwaVLoss()

    def forward(self, x):
        x = self.backbone(x).flatten(start_dim=1)
        x = self.projection_head(x)
        x = nn.functional.normalize(x, dim=1, p=2)
        p = self.prototypes(x)
        return p

    def training_step(self, batch, batch_idx):
        self.prototypes.normalize()
        crops, _, _ = batch
        multi_crop_features = [self.forward(x.to(self.device)) for x in crops]
        high_resolution = multi_crop_features[:2]
        low_resolution = multi_crop_features[2:]
        loss = self.criterion(high_resolution, low_resolution)
        return loss

    def configure_optimizers(self):
        optim = torch.optim.Adam(self.parameters(), lr=0.001)
        return optim
```

**Comment by philippmwirth** [comment]
You are using 512 prototypes (see `n_prototypes=512`) so the output of the forward pass is 512-dimensional.
