### ISSUE TITLE
Add: Histogram equalization augmentation

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#105]
As implemented in [PIL.ImageOps](https://pillow.readthedocs.io/en/3.0.x/reference/ImageOps.html#PIL.ImageOps.equalize). May be used to replace ImageNet normalization when working on X-ray images. This normalization increases contrast in the image.

Example:
- [COVID-19 DETERIORATION PREDICTION VIA SELF-SUPERVISED REPRESENTATION LEARNING  AND MULTI-IMAGE PREDICTION](https://arxiv.org/pdf/2101.04909.pdf)

**Comment by guarin** [comment]
I'll close this as the feature has been added to torchvision: https://pytorch.org/vision/main/generated/torchvision.transforms.RandomEqualize.html#randomequalize
