### ISSUE TITLE
Is there a way to use the trained model to check whether the input image in production is out of distribution?

### ISSUE THREAD

**Issue by sarmientoj24** [lightly-ai/lightly#1054]
Embeddings of images using lightly can produce some form of "distribution". Is there an established way on how to use the ttrained model to test whether a new image is out of distribution?

**Comment by guarin** [comment]
Hi @sarmientoj24, a possible approach is to use a K-Nearest Neighbors classifier to test whether an embedding of a new image is close to the embeddings of your train images. Similarly, DBSCAN can also be used for out of distribution detection. The out of distribution detection field is quite big and depending on the task there might be better methods specific for your case. This paper lists a lot of possible methods: https://arxiv.org/abs/2110.11334
