### ISSUE TITLE
Move config files and setup.py to pyproject.toml

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1085]
We would like to move to `pyproject.toml` for package configuration. @SauravMaheshkar made a PR (#1081 ) for this but it turned out to be more involved than expected.

TODO:
- [x] Figure out how to move everything from `setup.py` to `pyproject.toml`
- [x] Move `setup.py` and test on old python versions (3.6, 3.7)
- [x] Check if we have to upgrade `setuptools` dependency (`setuptools` only supports `pyproject.toml` from version 61.0.0)
- [x] Move other configuration files to `pyproject.toml`
    - [x] (skip) `pylintrc`
    - [x] `.coveragerc` 
    - [x] `mypy.ini`
- [x] Check if we can also move requirement files to `pyproject.toml`

**Comment by SauravMaheshkar** [comment]
@guarin Maybe we could break this down into smaller tasks and try to achieve this using subsequent smaller PRs. I think the easiest to start would be moving `coverage` and `mypy.ini` into `pyproject.toml`. Skipping `pylint` for now since it's rather verbose.

**Comment by guarin** [comment]
Hi, yes `.coveragerc` or `mypy.ini` could be a good start and a PR would be very welcome. I agree that adding `pylint` doesn't make sense for now, especially because we don't enforce linting right now.

**Comment by SauravMaheshkar** [comment]
@guarin with #1549 merged what parts of the above checklist are still to be fixed considering #1149 as well.

**Comment by philippmwirth** [comment]
Thanks for your work, @SauravMaheshkar. I have updated the original comment to track progress.

**Comment by philippmwirth** [comment]
I think a good next step would be to move the dependencies from `requirements/*.txt` to the `pyproject.toml`. Let's try to maintain the structure (base, dev, minimal, etc): https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-and-requirements

**Comment by SauravMaheshkar** [comment]
> I think a good next step would be to move the dependencies from `requirements/*.txt` to the `pyproject.toml`. Let's try to maintain the structure (base, dev, minimal, etc): https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-and-requirements

Thanks will work on that next !

**Comment by guarin** [comment]
Completed in #1559
