### ISSUE TITLE
'lightly.utils' has no attribute 'debug' with version 1.3.0

### ISSUE THREAD

**Issue by faris-k** [lightly-ai/lightly#1087]
Installing lightly version 1.3.0 leads to the following error when trying to use `lightly.utils.debug`. Was `debug` deprecated in the latest release?

```
AttributeError: module 'lightly.utils' has no attribute 'debug'
```

I was able to reproduce this issue by pip-installing `lightly==1.3.0` in **fresh** virtual environments on Windows and Linux, but oddly enough I wasn't able to reproduce the issue in colab 😕.

The second most recent version (`lightly==1.2.47`) does not give me this issue.

**Comment by philippmwirth** [comment]
Hi @faris-k, this is because we changed how submodules are imported in `1.3.0`. Instead of 
```python
import lightly

lightly.utils.debug.xyz
```
please use
```python
from lightly.utils import debug

debug.xyz
```

**Comment by faris-k** [comment]
Thank you @philippmwirth for clarifying this! Everything works now 😅
