### ISSUE TITLE
VicREGL incorrect use of global-local crops

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1107]
Our VicREGL implementation creates one view with 224px crops and one with 96px crops. The loss is then calculated between the crops with different sizes.

The original VicREGL implementation creates 2 views with 224px crops and optionally more views with 96px crops. The paper mentions that they didn't get the multi-crop strategy with 96px crops working when using a normal resnet:

> Surprisingly, we found that the combination of multi-crop with encoders from the ResNet family and the VICReg criterion is extremely difficult to optimize, and haven’t been able to make it work properly. 

Our implementation has the following issues:
* We create only a single 224px view but VicREGL uses two 224px views by default
* We create only a single 96px view but VicREGL uses zero 96px views by default
* The VicREGL collate and transform are limited to generating only a single view for each crop size
* The VicREGLLoss calculates the loss only between the 224px and 96px views but doesn't support more views

To fix the issues we'll have to make breaking changes to the collate, transform, and examples.

**Comment by ibro45** [comment]
Was this fixed by https://github.com/lightly-ai/lightly/pull/1122?

**Comment by guarin** [comment]
Yes! I forgot to close this issue :)

**Comment by guarin** [comment]
You are right that it is never used. Looks like it is a leftover from the original implementation. The authors code also returns image height and width here:
https://github.com/facebookresearch/VICRegL/blob/803ae4c8cd1649a820f03afb4793763e95317620/transforms.py#L154

But then never uses it to create the actual grid:
https://github.com/facebookresearch/VICRegL/blob/803ae4c8cd1649a820f03afb4793763e95317620/transforms.py#L210

I believe we can just remove it from our code :)
