### ISSUE TITLE
Modify the lightly dataset to load one more set of mask data besides the original dataset

### ISSUE THREAD

**Issue by AricYang** [lightly-ai/lightly#1117]
I'm trying to add one more set of mask images into my lightly SSL model, which will go through different layers than the original image. The original image goes through ordinary resnet18 layers, the mask image only goes through layers of avgpooling layer, and the pooled mask image will serve as a filter for each corresponding convoluted original image.
My problem now is that lightly dataset only accepts 1 sets of data, is there any way to modify the lightly dataset to load and return 2 sets of data? Or are there any ways to bypass this restriction and provide the 2nd set of data to the model within the lightly structure?

**Comment by AricYang** [comment]
Thank you for answering! @guarin .
The 1st dataset is a set of 512x512 RGB image with its fourth channel as transparency value which distinguishes background and foreground pixels. But to be loaded as Lightlydataset, the image turned into a pure RGB image with 3 channels.
The 2nd dataset is a set of 512x512 black and white images extracted from the 1st dataset's background, and foreground value, in which all the foreground is white and the background is black.

What I'm aiming to do is to generate representations that only consider the foreground elements and exclude the background elements.

Specifically, I'm thinking to add another line of forward function which takes the 2nd foreground/background dataset through layers of average pooling layers until the shape( in my case 16x16 pixels) matches the final feature map (after final convolution,  before flattening) of 1st dataset which went through conventional convolution process. The product of 2nd dataset will serve as a filter to filter out background pixels and give corresponding weight to foreground pixels depending on the intensity of the pooled foreground value, then the filtered feature map will be summed element-wise within the same feature and divided by the element-wise sum of the corresponding filter to produce an (n features, 1, 1) vector as representation.

So my goal will be to set the 2nd dataset to the dataloader and also construct an addition forward function that takes the 2nd dataset through layers of average pooling and generate a filter for the 1st forward function.

I'm still a novice using lightly SSL, so can I get some directions or suggestions on the goal I'm about to achieve?

**Comment by guarin** [comment]
Hi, I think in your case it might be easier to create a custom torch dataset class. The reason is that you want to load the rgb and the black/white image at the same time. You will also have to be careful with augmentations. Because if you do random cropping you will have to crop the same regions in the rgb and the black/white images.

Something like this might work. I didn't test it but it should get you started:
```
import glob
from torch.utils.data import Dataset, DataLoader
from PIL import Image

class CustomDataset(Dataset):
	def __init__(input_dir, transform):
		self.input_dir = input_dir
		self.image_filepaths = glob.glob(f"{input_dir}/**/*.jpg", recursive=True)
		self.transform = transform

	def __len__(self):
		return len(self.image_filepaths)

	def __getitem__(self, idx):
		filepath = self.image_filepaths[idx]
		with open(filepath, "r") as file:
			image = Image.open(file)
			rgb_image = ...
			black_white_image = ...

		rgb_image, black_white_image = self.transform(rgb_image, black_white_image)
		return [rgb_image, black_white_image], 0, filepath


def transform(rgb_image, black_white_image):
	# apply transforms here
	# make sure that any cropping is done the same on rgb_image
	# and black_white_image
	...


dataset = CustomDataset("/datasets/my_dataset", transform=transform)
collate_fn = MultiViewCollate()
dataloader = DataLoader(
	dataset,
	batch_size=128,
	collate_fn=collate_fn,
)


for (rgb_images, black_white_images), _, _ in dataloader:
	# rgb_images has shape (batch_size, 3, H, W)
	# black_white_images has shape (batch_size, H, W)
	model(rgb_images, black_white_images)
```

**Comment by AricYang** [comment]
Thank you so much @guarin ! according to your example I code my own custom dataset and model structure.

However, I got ValueError: 
expected 4D input (got 3D input)

I think it might lost batch size information somewhere, would you check my code to see where the error might occur?
RGB image goes through augmentation and to tensor without resizing or cropping.
BG mask image goes through only to tensor.

dataset:

class Dataset(BaseDataset):
    
    def __init__(self, 
                 image_dir,
                 mask_dir,
                 preprocessing_image = None,
                 preprocessing_mask = None,
                ):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.preprocessing_image = preprocessing_image
        self.preprocessing_mask = preprocessing_mask
    
    def __getitem__(self, idx):
        filepath = self.image_dir[idx]
        
        image = cv2.imread(self.image_dir[idx])
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(image)
        
        mask = cv2.imread(self.mask_dir[idx])
        mask = Image.fromarray(mask)
        
        if self.preprocessing_image:
            image = self.preprocessing_image(image)
            
        if self.preprocessing_mask:
            mask = self.preprocessing_mask(mask)
            
        return [image, mask], 0, filepath
    
    def __len__(self):
        return len(self.image_dir)
        
Model:

class BarlowTwins_MP(pl.LightningModule):
    def __init__(self):
        super().__init__()
        resnet = torchvision.models.resnet18()
        self.backbone = nn.Sequential(*list(resnet.children())[:-2])
        self.projection_head = BarlowTwinsProjectionHead(512, 2048, 2048)
        self.criterion = BarlowTwinsLoss()
        avgpool = torch.nn.AvgPool2d(kernel_size=3, stride=2, padding=1, ceil_mode=False)
        self.avgpool_5 = nn.Sequential(avgpool,
                                       avgpool,
                                       avgpool,
                                       avgpool,
                                       avgpool)

    def maskpool(self, y):
        y = self.avgpool_5(y)
        y = y[0][0]
        y = torch.round(y, decimals = 3)
        
        return y
        
    def forward(self, x):
        x = self.backbone(x)
        return z

    def training_step(self, batch, batch_index):
        ([x0,y0], [x1,y1]), _, _ = batch
        
        y = self.maskpool(y0)
        
        
        x0 = self.forward(x0)
        x0 = (x0*y).sum()/y.sum()
        x0 = x0.flatten(start_dim=1)
        z0 = self.projection_head(x0)
        
        x1 = self.forward(x1)
        x1 = (x1*y).sum()/y.sum()
        x1 = x1.flatten(start_dim=1)
        z1 = self.projection_head(x1)
        
        loss = self.criterion(z0, z1)
        return loss

    def configure_optimizers(self):
        optim = torch.optim.SGD(self.parameters(), lr=0.06)
        return optim
    
model = BarlowTwins_MP()

**Comment by guarin** [comment]
Which collate function do you use in your dataloader? My guess would be that the batch unpacking doesn't work as expected:
```
([x0,y0], [x1,y1]), _, _ = batch
```

With `MultiViewCollate` you should get:
```
(images, masks), _, _ = batch
# images and masks have shape (B, C, H, W)
```

**Comment by AricYang** [comment]
I didn't use a collate function since the image and mask go through different transformation. I apply the transformation when defining the custom dataset.

class GaussianNoise:
    def __call__(self, sample: torch.Tensor) -> torch.Tensor:
        mu = sample.mean()
        snr = np.random.randint(low=4, high=8)
        sigma = mu / snr
        noise = torch.normal(torch.zeros(sample.shape), sigma)
        return sample + noise
    
# Augmentation settings

# compose the custom augmentations with available augmentations
# T.colorJitter(brightness, contrast, saturation, hue)
color_jitter = T.ColorJitter(0.1, 0.1, 0.1, 0.05)
normalize: dict = {'mean': [0.7253, 0.4861, 0.6496], 'std': [0.1773, 0.1977, 0.1369]}
# defining image transformation
transform_image = torchvision.transforms.Compose([
    torchvision.transforms.RandomHorizontalFlip(p=0.5),
    torchvision.transforms.RandomVerticalFlip(p=0.5),
    T.RandomApply([color_jitter], p=0.8),
    T.RandomApply([torchvision.transforms.GaussianBlur(21)], p = 0.3),
    torchvision.transforms.ToTensor(),
    GaussianNoise(),
    T.Normalize(mean=normalize["mean"], std=normalize["std"])
])

# defining mask transformation
transform_mask = torchvision.transforms.ToTensor()

then define my dataset as follows:
dataset = Dataset(image_dir, mask_dir, preprocessing_image = transform_image, preprocessing_mask = transform_mask)

**Comment by guarin** [comment]
Could you print the shapes of the tensors in the batch?
```
def training_step(self, batch, batch_index):
    ([x0,y0], [x1,y1]), _, _ = batch
    print(x0.shape, y0.shape, x1.shape, y1.shape)
```

**Comment by guarin** [comment]
You don't have to implement it. It is already in Python: https://docs.python.org/3/library/functions.html#print

**Comment by AricYang** [comment]
Oh thats not what I mean, but I figure out it anyway.
The printed shapes are:
torch.Size([3, 512, 512]) torch.Size([3, 512, 512]) torch.Size([3, 512, 512]) torch.Size([3, 512, 512])

**Comment by guarin** [comment]
It looks like you are indeed missing the batch dimension. You can add a batch dimension to your tensors before passing them to the model:
```
x0 = self.forward(x0.unsqueeze(0)) # converts from (3, 512, 512) to (1, 3, 512, 512)
```

**Comment by AricYang** [comment]
Hi @guarin , thank you for the suggestions. I changed the way I define my custom dataset and the structure of my model class. The training starts running but the loss doesn't drop. The following code is the new version of my code:
class Dataset(BaseDataset):
    
    def __init__(self, 
                 image_dir,
                 mask_dir,
                 preprocessing_image = None,
                 preprocessing_mask = None,
                ):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.preprocessing_image = preprocessing_image
        self.preprocessing_mask = preprocessing_mask

    def __len__(self):
        return len(self.image_dir)
    
    def __getitem__(self, idx):
        filepath = self.image_dir[idx]
        
        image = cv2.imread(self.image_dir[idx])
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image_v1 = Image.fromarray(image)
        image_v2 = copy.deepcopy(image_v1)
        
        mask = cv2.imread(self.mask_dir[idx])
        mask = Image.fromarray(mask)
        
        if self.preprocessing_image:
            image_v1 = self.preprocessing_image(image_v1)
            image_v2 = self.preprocessing_image(image_v2)
            
        if self.preprocessing_mask:
            mask = self.preprocessing_mask(mask)
            
        return image_v1,image_v2, mask, 0, filepath

**Comment by AricYang** [comment]
Hi @guarin , thank you for the suggestions. I changed the way I define my custom dataset and the structure of my model class. The training starts running but the loss doesn't drop. The following code is the new version of my code:
```
class Dataset(BaseDataset):

def __init__(self, 
             image_dir,
             mask_dir,
             preprocessing_image = None,
             preprocessing_mask = None,
            ):
    self.image_dir = image_dir
    self.mask_dir = mask_dir
    self.preprocessing_image = preprocessing_image
    self.preprocessing_mask = preprocessing_mask

def __len__(self):
    return len(self.image_dir)

def __getitem__(self, idx):
    filepath = self.image_dir[idx]
    
    image = cv2.imread(self.image_dir[idx])
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image_v1 = Image.fromarray(image)
    image_v2 = copy.deepcopy(image_v1)
    
    mask = cv2.imread(self.mask_dir[idx])
    mask = Image.fromarray(mask)
    
    if self.preprocessing_image:
        image_v1 = self.preprocessing_image(image_v1)
        image_v2 = self.preprocessing_image(image_v2)
        
    if self.preprocessing_mask:
        mask = self.preprocessing_mask(mask)
        
    return image_v1,image_v2, mask, 0, filepath
```
   this dataset return 5 arguments, image_v1 and image_v2 is 2 variants from a same original image. I don't know if it is the correct way to return arguments like this in my case.
   
```
class BarlowTwins_MP(pl.LightningModule):
    def __init__(self):
        super().__init__()
        resnet = torchvision.models.resnet18()
        self.backbone = nn.Sequential(*list(resnet.children())[:-2])
        self.projection_head = BarlowTwinsProjectionHead(512, 2048, 2048)
        self.criterion = BarlowTwinsLoss()
        avgpool = torch.nn.AvgPool2d(kernel_size=3, stride=2, padding=1, ceil_mode=False)
        self.avgpool_5 = nn.Sequential(avgpool,
                                       avgpool,
                                       avgpool,
                                       avgpool,
                                       avgpool)

    def maskpool(self, y):
        y = self.avgpool_5(y)
        y = y[0][0].unsqueeze(0).unsqueeze(0) # turn shape(batch_size,3,W,H) into (1, 1, W, H)
        y = torch.round(y, decimals = 3)
    
        return y
    
    def forward(self, x):
        x = self.backbone(x)
        return x

    def training_step(self, batch, batch_index):
        x0, x1, y, _, _ = batch

        y = self.maskpool(y)

        x0 = self.forward(x0) # foward image tensor through resnet 18 backbone[-2],torch.Size([batchsize, 512, 16, 16])
        x0 = (x0*y).sum([2,3]) # apply mask filter to image representation, and sum all element within a feature,torch.Size([batchsize, 512])
        x0 = x0/(y.sum()) # average the value with sum of mask filter element,torch.Size([batchsize, 512])
        z0 = self.projection_head(x0)

        x1 = self.forward(x1) # foward image tensor through resnet 18 backbone[-2]
        x1 = (x1*y).sum([2,3]) # apply mask filter to image representation, sum all element within a feature
        x1 = x1/(y.sum()) # average the value with sum of mask filter element
        z1 = self.projection_head(x1)
    
        loss = self.criterion(z0, z1)
        return loss

    def configure_optimizers(self):
        optim = torch.optim.SGD(self.parameters(), lr=0.06)
        return optim
    
model = BarlowTwins_MP()
```
This model code raise a ValueError "Expected more than 1 value per channel when training, got input size torch.Size([1, 2048])" in the following line when I'm testing the code with batch size 1, but not with 2
```
z0 = self.projection_head(x0)
```

Did I made any mistake in passing the arguments or I misuse the self.projection_head() function?

**Comment by AricYang** [comment]
Update: The loss is indeed decreasing, it just not as fast as I expected.
Thank you @guarin, I'm not able to construct my model without your help!
