### ISSUE TITLE
Enable accelerator: "auto" and devices: "auto"

### ISSUE THREAD

**Issue by julien-blanchon** [lightly-ai/lightly#1158]
Enable the usage of:
```yaml
accelerator: "auto"
devices: "auto"
``` 
In config.yaml

The following line disable this behaviour: https://github.com/lightly-ai/lightly/blob/527572e2bef6d4df4b96dbe3c2a5e46e36ae1528/lightly/cli/train_cli.py#L49-L55

I think the usage of auto should be the default instead of `"gpu" if torch.cuda.is_available() else "cpu"`, as many other accelerator such as `mps` are emerging.

**Comment by guarin** [comment]
Hi @julien-blanchon, thanks for the issue. You are right that we should update this and use `"auto"` by default.
