### ISSUE TITLE
CUDA errors in NTXentLoss with gloo backend in multi-gpu training 

### ISSUE THREAD

**Issue by mkirchler** [lightly-ai/lightly#1176]
I was wondering if the `gloo` distributed communication package for multi-gpu training is officially supported by lightly. It seems like e.g. NTXentLoss doesn't work with `gloo` (I'm using pytorch lightning): I get CUDA errors, even when setting `gather_distributed = False`.
I can fix the issue when using `gather_distributed = False` by replacing the line
https://github.com/lightly-ai/lightly/blob/master/lightly/loss/ntx_ent_loss.py#L164
by
```python
labels = labels + batch_size * (dist.rank() if gather_distributed else 0)
```
but then of course I can't use `gather_distributed = True` anymore. 

Using the `nccl` backend, everything works fine, but `nccl` is not working well on some of our machines, so unfortunately I'm stuck with `gloo`. I think using `gloo` might be too much of an exception to fix the problem for `gather_distributed = True`, but maybe it'd help to just replace the line above and mention somewhere in the documentation that `gather_distributed` is not supported for `gloo`?

**Comment by guarin** [comment]
Hi, gather is not supported for gpus with the `gloo` backend, see: https://pytorch.org/docs/stable/distributed.html#backends

**Comment by guarin** [comment]
You are right, I made a PR to fix it. Let me know if this solves your problem.

**Comment by mkirchler** [comment]
Yes, looks good to me, thank you!
