### ISSUE TITLE
Adapting VICRegL to 3D images

### ISSUE THREAD

**Issue by ibro45** [lightly-ai/lightly#1178]
@guarin @Ra1Nik

Hi! I'm trying to adapt `VicRegL` to work with 3D images. So far, I implemented 3D transformations and appropriate grid creation, but I am running into some issues with the loss. I won't bother you with the particular problem that I'm running into as it isn't expected really from `lightly` to support 3D images. However, I wanted to ask you if you could give some advice as to what parts of the `VICReg` and `VICRegL` code I should change or pay close attention to. Of course, only if you have time for it.

Thank you so much for all the work you're doing with `lightly`, without it, SSL experimentation would be way more difficult!

**Comment by guarin** [comment]
Hi, I saw that you created another issue, is there anything else we can help you with? I think you already found the difficult part 😅
