### ISSUE TITLE
Update PIP API to follow mapping from filenames to ids

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#118]
As described in  https://github.com/lightly-ai/lightly-core/issues/123, the pip package needs a mapping from the following four representations of the samples belonging to a tag:
1. bitmask: str / List[bit], length: #NoSamplesInDataset
2. sample_indexes: List[int], length: #NoSamplesInTag
3. filenames: List[str], length: #NoSamplesInTag
4. sampleIDs: List[MongoObjectID] / List[str], length: #NoSamplesInTag

The mapping can be done using the following two lists downloaded from the API:
- A) all_filenames: List[str], length: #NoSamplesInDataset
- B) all_ sampleIDs: List[MongoObjectID] / List[str], length: #NoSamplesInDataset

Following mapping functions are needed:
- [x] from 1. to 2.: implemented in the bitmask class
- [x] from 2. to 3. by simple indexing, using A)
- [x] from 2. to 4. by simple indexing, using B)

- [x] from 4. to 2. by [reverse indexing](https://stackoverflow.com/questions/26569855/finding-the-indices-of-the-values-of-one-list-in-another-list) using A)
- [x] from 4. to 3. by [reverse indexing](https://stackoverflow.com/questions/26569855/finding-the-indices-of-the-values-of-one-list-in-another-list) using B)
- [x] from 2. to 1.: implemented in the bitmask class

Furthermore, the following workflows have to be updated to use these mappings:
- [x] Upload of embeddings: order them by the order in the initial tag
- [ ] Creating a new tag from a custom selected subset (e.g. defined by filenames)

**Comment by IgorSusmelj** [comment]
The upload of samples is not affected. We upload the samples once when the dataset is created and after the initial tag we "freeze" it. That's the moment where we create the mapping. So we only need to take care of the mapping during the upload of the embeddings. Before we upload the embedding we need to reorder the csv file according to the mapping of the dataset.
The trigger of the basic sampling is described in the openAPI specs. We just pass the tagIds.
