### ISSUE TITLE
Cleanup transforms docstrings

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1223]
Cleanup docstrings in `lightly/transforms` subpackage.

**Comment by IgorSusmelj** [comment]
We should also make sure that all the transforms describe in detail what they do. E.g. for the SimCLR transform (https://docs.lightly.ai/self-supervised-learning/lightly.transforms.html#lightly.transforms.simclr_transform.SimCLRTransform) we should mention the expected input and output as well as all operations that we apply.
