### ISSUE TITLE
VICRegL drop default vertical flip

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1240]
We accidentally pass the horizontal flip probability also as vertical flip probability in `RandomResizedCropAndFlip` transform from `VICRegL`: https://github.com/lightly-ai/lightly/blob/61127338eacd50ad977b9eebaa7a297c404fecb9/lightly/transforms/random_crop_and_flip_with_grid.py#L151-L152

We should fix this by adding vertical flip probability as argument to the class and passing it accordingly to `RandomVerticalFlipWithLocation`. The default vertical flip probability for `VICRegL` should be `0` as only horizontal flip is used.

**Comment by iamharsha1999** [comment]
Hi @guarin can you assign this issue to me. Would like to try out.

**Comment by guarin** [comment]
Sure!
