### ISSUE TITLE
Runtime Error: lightly BYOL with YOLOv3 backbone 

### ISSUE THREAD

**Issue by kalikhademi** [lightly-ai/lightly#1274]
Hi, 

I have used the BYOL example at this link to train YOLOv3 backbone:
https://docs.lightly.ai/self-supervised-learning/examples/byol.html

`
   model = YOLO('yolov3.yaml')
   backbone = Sequential(*list(model.model.children())[0][:10], AdaptiveAvgPool2d((1, 1))) 
   class BYOL(pl.LightningModule):

   def __init__(self):
   super().__init__()
   self.backbone = backbone
    self.projection_head = BYOLProjectionHead(256, 1024, 256)
    self.prediction_head = BYOLPredictionHead(256, 1024, 256)
    model = BYOL()
    dataset = LightlyDataset(img_folder)
   #create the trainer and fit the trainer
`
I recived RuntimeError as follows:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x1024 and 256x1024)

Epoch 0:   0%|          | 0/1576 [00:43<?, ?it/s]c1000a-s11:43574:58630 [0] NCCL INFO [Service thread] Connection closed by localRank 0

Could you help me to solve this?

Thanks,

**Comment by kalikhademi** [comment]
I figured it out!The dimension of projection head should be (1024,1024,256) as the dimensional output of YOLOv3 is 1024.

**Comment by sergiev** [comment]
@kalikhademi does your backbone weights differ after BYOL? Mine does not (on yolov5), looking for reasons
