### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by opencomvis** [lightly-ai/lightly#1279]
I am using the example in [FastSiam](https://docs.lightly.ai/self-supervised-learning/examples/fastsiam.html)
and used the custom dataset. `dataset = LightlyDataset("path/to/folder", transform=transform)`
exactly the same code, my dataset folders look like:
``image1.jpg
image2.jpg
.
.
.
imageN.jpg``
However, I got the following error: 

valueerror: too many values to unpack (expected 2) pytorch

**Comment by philippmwirth** [comment]
That's because iterating over the `LightlyDataset` always returns `tuple[img, label, filename]` where `label` is the index of the subdirectory the image is in.  Change 
```python
for views, _ in dataloader:
```
to 
```python
for views, _, _ in dataloader:
```
and it should work.

@guarin we should probably make this self-evident in the tutorials.

**Comment by guarin** [comment]
Yes we should change the examples to:

```
for batch in dataloader:
   views = batch[0]
```
