### ISSUE TITLE
Bug in PMSNLoss

### ISSUE THREAD

**Issue by Cloudy1225** [lightly-ai/lightly#1340]
Nice implementation of the [PMSNLoss](https://github.com/lightly-ai/lightly/blob/ddfed3c4dc03a8d2722df24bfa537d24ac80bde6/lightly/loss/pmsn_loss.py)! But the computation of Kullback-Leibler divergence missed `.log()` in Line 71&142.

**Comment by guarin** [comment]
Hi, thanks for using Lightly and reporting the issue! You are right, I just made a PR to fix it.
