### ISSUE TITLE
Incorrect training batch

### ISSUE THREAD

**Issue by CHYjeremy** [lightly-ai/lightly#1361]
Hi guys,

When i am training a custom dataset of ~10000 images, tqdm, when training, shows the following pic

`/home/hychen/lightly_simclr/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:281: PossibleUserWarning: The number of training batches (24) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 26: 100%|███████████████████████████████████████████████████| 24/24 [00:11<00:00,  2.08it/s, v_num=0]`

i set batch size to be 128.

As you could see, the training-batch is 24, which is smaller than (10000/128), could i ask what is the reason please?

Thanks!

**Comment by guarin** [comment]
Hi, thanks for using Lightly!

Are you sure that the training set of your dataset has 10000 images and batch size 128? Note that this error comes from PyTorch Lightning and not from Lightly, you might want to ask on their forum/discord for additional help.
