### ISSUE TITLE
[Active Learning] Compute Active learning scores for object detection

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#137]
Create a scorer for object detection that can compute scores like prediction entropy, ...

Input of predictions:
For each of the N samples, there are B bounding boxes giving the probability of one of the C classes.

- [x] Find a good way to represent the model predictions of an object detection model
- [x] Decide which kind of models to support (Yolo, SSD, ...), see also https://heartbeat.fritz.ai/a-2019-guide-to-object-detection-9509987954c3
- [x] Decide which kinds of scores to compute and find a good way to compute them, e.g. see https://heartbeat.fritz.ai/a-2019-guide-to-object-detection-9509987954c3 or https://arxiv.org/pdf/2004.04699.pdf
- [x] Implement it

**Comment by IgorSusmelj** [comment]
Regarding the input of the scorer. From my experience there are two common formats for bounding box predictions:

N: number of samples, C: number of classes
- N x (5 + C), when we have 4 values for bbox coordinates + 1 value for objectness score and then C values for the classes
- N x (4 + C) the same but without an objectness score

Do you know any other common formats?

**Comment by philippmwirth** [comment]
Just a minor correction: N should  be the number of boxes.

Then there's also the case where the output of the model is
- N x 4 or N x 5, when the model does not provide a class distribution but only a single label (e.g. torchvision fasterrcnn)


My suggestion is to accept a list of dictionaries (each dictionary corresponds to one image)
```
{
    boxes: [[]] # list of list of coordinates (either x0,y0,x1,y1 or x0,y0,w,h)
    scores: [] # list of confidence scores (one for each bounding box)
    probabilities: [[]] # list of list of class probabilities
}
```
(all lists can be replaced by numpy arrays or tensors, whatever you want)

The above approach is pretty minimal but I think it should be OK for starters. I would then add other Scorers which handle other output formats (e.g. if there's only a label and no class probabilities).

**Comment by IgorSusmelj** [comment]
> Just a minor correction: N should be the number of boxes.
> 
> Then there's also the case where the output of the model is
> 
> * N x 4 or N x 5, when the model does not provide a class distribution but only a single label (e.g. torchvision fasterrcnn)
> 
> My suggestion is to accept a list of dictionaries (each dictionary corresponds to one image)
> 
> ```
> {
>     boxes: [[]] # list of list of coordinates (either x0,y0,x1,y1 or x0,y0,w,h)
>     scores: [] # list of confidence scores (one for each bounding box)
>     probabilities: [[]] # list of list of class probabilities
> }
> ```
> 
> (all lists can be replaced by numpy arrays or tensors, whatever you want)
> 
> The above approach is pretty minimal but I think it should be OK for starters. I would then add other Scorers which handle other output formats (e.g. if there's only a label and no class probabilities).

I updated the proposal. I forgot about the boxes. A dictionary would work as well. However, we should also streamline the interface. For classification, we don't use a dictionary. I would keep it simple and stupid :)
So either we switch to dictionaries for both or we go with numpy arrays for both? Or any other idea?

**Comment by philippmwirth** [comment]
If not a dictionary, we can also switch to a numpy array. I just see a few problems there:
- Not all images have an equal amount of bounding boxes -> need to add some kind of padding.
- Either we have a 3-dimensional numpy array where the first dimension is "image" or we use a 2-dimensional numpy array but then we need to map the rows to images (i.e. each image has a certain range of rows)

The thing about having a list of dictionaries is that it's super easy and intuitive to use. One alternative would be to use a list of numpy arrays instead, where each numpy array has shape B_i x (5 + C) where B_i is the number of boxes on image i.

Opinions? @MalteEbner @IgorSusmelj

**Comment by IgorSusmelj** [comment]
I would go for refactoring and use dictionaries everywhere.

**Comment by MalteEbner** [comment]
I would go with the list of dictionaries as Philipp proposed for object detection.

However, I would keep the np.ndarray for classification, as it is the usual output of a classifier.

**Comment by IgorSusmelj** [comment]
> I would go with the list of dictionaries as Philipp proposed for object detection.
> 
> However, I would keep the np.ndarray for classification, as it is the usual output of a classifier.

Ok, let me draft my PR and then we can go from there

**Comment by philippmwirth** [comment]
Following our discussion, we'll have the following classes:

```python
class BoundingBox:

    def __init__(self, x0, y0, x1, y1):
        ...

    @classmethod
    def from_x_y_w_h(self, x, y, w, h):
        ...

    ...
```


```python
class ObjectDetectionOutput:

    def __init__(self,
                 boxes: List[BoundingBox],
                 scores: List[float],
                 labels: List[int]):
    ...


    @classmethod
    def from_class_probabilities(self,
                 boxes: List[BoundingBox]
                 object_probabilities: List[float],
                 class_probabilities: List[List[float]],
                 labels: List[int]):
    # calculate scores = object_probabilities * max(class_probabilities)
    ...

```

```python
class ScorerObjectDetection:

    def __init__(self, List[ObjectDetectionOutput]):
        ...

```

Good thing is that with the scores we can still calculate the `prediction_margin` (which we also have in classification) so we can simply change our default score in the worker to `prediction_margin` for the moment and it will work with classification and object detection.

Note that I accept labels because later we can add balancing scores etc.

@IgorSusmelj and @MalteEbner can you give me a quick round of feedback before I start implementing?
