### ISSUE TITLE
Type check lightly.api

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#1387]
# Type check lightly.api

* Work through the excluded files with prefix `lightly/api` and `tests/api` in [pyproject.toml](https://github.com/lightly-ai/lightly/blob/master/pyproject.toml#L184) and type check one by one.
* Remove `follow_imports = skip` for `lightly.api.*`.

Note: Typing the `ApiWorkflowClient` is a bit tricky because of the mixins. Mypy recommends typing mixins by making them implement a Protocol (see [documentation](https://mypy.readthedocs.io/en/latest/more_types.html#mixin-classes)).

**Comment by SauravMaheshkar** [comment]
Closed in favour of #1635
