### ISSUE TITLE
Type check lightly.cli

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#1388]
# Type check lightly.cli

* Work through the excluded files with prefix lightly/cli and tests/cli in [mypy.ini](https://github.com/lightly-ai/lightly/blob/master/mypy.ini) and type check them one by one.
* Remove `follow_imports = skip` for `lightly.cli.*`.

**Comment by guarin** [comment]
Closed in favor of https://github.com/lightly-ai/lightly/issues/1635
