### ISSUE TITLE
Type check lightly.loss

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#1391]
# Type check lightly.loss

* Work through the excluded files with prefix lightly/loss and tests/loss in [mypy.ini](https://github.com/lightly-ai/lightly/blob/master/mypy.ini) and type check one by one.
* Remove `follow_imports = skip` for `lightly.loss.*`.

**Comment by SauravMaheshkar** [comment]
Can I take this up ?

**Comment by guarin** [comment]
Yes of course, thanks a lot! Will assign the issue to you.

**Comment by guarin** [comment]
Closed in favor of https://github.com/lightly-ai/lightly/issues/1635
