### ISSUE TITLE
Type check lightly.models

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#1392]
# Type check lightly.models

* Work through the excluded files with prefix lightly.models and tests/models in [mypy.ini](https://github.com/lightly-ai/lightly/blob/master/mypy.ini) and type check one by one.
* Work through the excluded files with prefix lightly/models/heads and tests/models/heads in [mypy.ini](https://github.com/lightly-ai/lightly/blob/master/mypy.ini) and type check one by one.
* Remove `follow_imports = skip` for `lightly.models.*`.

Note: It's not necessary to type-check the following deprecated full implementations:
* `lightly.models.barlowtwins`
* `lightly.models.byol`
* `lightly.models.moco`
* `lightly.models.nnclr`
* `lightly.models.simclr`
* `lightly.models.simsiam`

**Comment by guarin** [comment]
Closed in favor of https://github.com/lightly-ai/lightly/issues/1635
