### ISSUE TITLE
Type check lightly.utils.benchmarking

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#1393]
# Type check lightly.utils.benchmarking

* Work through the excluded files with prefix `lightly/utils/benchmarking` and `tests/utils/benchmarking` in [mypy.ini](https://github.com/lightly-ai/lightly/blob/master/mypy.ini) and type check one by one.
* Remove `follow_imports = skip` for `lightly.utils.benchmarking.*`.

**Comment by guarin** [comment]
Closed in favor of https://github.com/lightly-ai/lightly/issues/1635
