### ISSUE TITLE
Number of training iterations more than what it should be in an epoch

### ISSUE THREAD

**Issue by sadimanna** [lightly-ai/lightly#1406]
I am training BYOL with a BS of 256 on ImageNet100

After running main.py from the ImageNet benchmark scripts, I see that the number of iterations is 1015 in a training epoch, which is double the number of iterations it should be (1300 * 100 / 256 = 507)

`Epoch 0:  48%|███████████████▎                | 486/1015 [10:14<11:08,  1.26s/it, loss=12.4, v_num=0, train_loss=-2.83] `

The `lightly.data.LightlyDataset` looks fine, however I cannot figure out why this strange error is occurring. 

This error is occurring when running Barlow Twins as well.

**Comment by guarin** [comment]
Hi! Could you post the exact command you are using? I get 507 batches with the following command:
```
python benchmarks/imagenet/resnet50/main.py --train-dir /datasets/imagenet100/train --val-dir /datasets/imagenet100/val --num-classes 100 --epochs 100 --num-workers 12 --devices 1 --batch-size-per-device 256 --methods byol
```
output:
```
Epoch 0:   0%|       | 0/507 
```

**Comment by sadimanna** [comment]
Hi @guarin 

I am getting 507 batches now. I just closed the terminal and ran the command again. I was using the same command as yours. I don't understand what just happened. Strange!!
