### ISSUE TITLE
Give a full tutorial on the docs.

### ISSUE THREAD

**Issue by atonyo11** [lightly-ai/lightly#1418]
Can you provide a complete example?
For example, in the [simclr tutorial](https://docs.lightly.ai/self-supervised-learning/tutorials/package/tutorial_simclr_clothing.html), the tutorial lack how to use the pre-trained model and train a classifier on top. How to use it on a custom dataset?

**Comment by guarin** [comment]
Hi!

You can find a tutorial on how to train a classifier on top of a model here: https://docs.lightly.ai/self-supervised-learning/tutorials/package/tutorial_moco_memory_bank.html# The tutorial uses MoCo but you can just replace the MoCo code with SimCLR.

Regarding custom data you can use any torchvision dataset, including [ImageFolder](https://pytorch.org/vision/main/generated/torchvision.datasets.ImageFolder.html) with custom images. Alternatively you can also use a `LightlyDataset` that is also showcased in the tutorial above.

**Comment by atonyo11** [comment]
I got it. Thank you!
