### ISSUE TITLE
Clarification: Why does KNN eval normalize the representations?

### ISSUE THREAD

**Issue by RylanSchaeffer** [lightly-ai/lightly#1425]
Why does KNN eval normalize the representations?

I'm specifically referring to [here](https://github.com/lightly-ai/lightly/blob/master/lightly/utils/benchmarking/knn_classifier.py#L103) and [here](https://github.com/lightly-ai/lightly/blob/master/lightly/utils/benchmarking/knn_classifier.py#L113).

Is this commonly done in the literature? It seems odd to normalize the representations before applying KNN.

**Comment by guarin** [comment]
Our implementation follows [InstDisc](https://arxiv.org/pdf/1805.01978v1.pdf) and [MoCo](https://github.com/facebookresearch/moco) which both apply normalization. For MoCo please see the colab notebook: https://colab.research.google.com/github/facebookresearch/moco/blob/colab-notebook/colab/moco_cifar10_demo.ipynb

**Comment by crazyboy9103** [comment]
When euclidean distance is used for the distance metric, it is in fact necessary to normalize the representations before applying knn. Take a look at: https://stats.stackexchange.com/questions/287425/why-do-you-need-to-scale-data-in-knn. However, for cosine similarity, it is not. But lightly's implementation of [knn_predict](https://github.com/lightly-ai/lightly/blob/master/lightly/utils/benchmarking/knn.py#L8) looks like it expects normalized representations, so i think their implementation is correct.

**Comment by RylanSchaeffer** [comment]
What that post/link does is different from what the code does, if I
understand correctly. The code normalizes to the hypersphere. The post does
not.

**Comment by RylanSchaeffer** [comment]
To clarify, I believe the post standardizes each dimension independently,
whereas the code performs L2 normalization. If I'm correctly understanding,
these are not the same.

**Comment by crazyboy9103** [comment]
You're correct, the post illustrates the importance of scaling when using euclidean distance as the similarity metric. For continuous values like representations, it is common to use cosine similarity, which includes L2 normalization (onto a unit hypersphere) to compare a pair of representations.

**Comment by guarin** [comment]
I don't think it is strictly necessary to normalize but many SSL methods use normalized embeddings or cosine similarity, making it also attractive for KNN evaluation, see [MoCo](https://github.com/facebookresearch/moco/blob/1999df86de600027cd2702cbd7cd7b7d2a53559d/moco/builder.py#L139) and [SimCLR](https://github.com/google-research/simclr/blob/383d4143fd8cf7879ae10f1046a9baeb753ff438/objective.py#L55). We also use normalization as we follow the MoCo implementation.

If a model was not trained using cosine similarity or normalization it might be beneficial to not use normalization for KNN as well.

**Comment by RylanSchaeffer** [comment]
Ok thank you both for clarifying! I can modify the class myself.

Short term, I think it might be reasonable to include a kwarg and a default parameter for the class.

More generally, I think it's a mistake to think that because the embeddings are normalized that the outputs of the backbone are normalized or should be normalized or can meaningfully be normalized. It's quite odd to see normalization to the hypersphere before kNN because the typical assumption of kNN is Eudlicean space.
