### ISSUE TITLE
VICReg Loss De-Means Twice?

### ISSUE THREAD

**Issue by RylanSchaeffer** [lightly-ai/lightly#1445]
https://github.com/lightly-ai/lightly/blob/66ad1b40ebf3b53512703c774988211ce283211f/lightly/loss/vicreg_loss.py#L128-L129

I think the VICReg loss removes the mean, then calls `.var()` which also de-means (see: https://pytorch.org/docs/stable/generated/torch.var.html). 

If I understand correctly, that seems unnecessary?

**Comment by philippmwirth** [comment]
Hi @RylanSchaeffer, thank you for bringing this up. I think you are right, the de-mean is only necessary for the covariance term.
