### ISSUE TITLE
Bug in MultiCropTransform class

### ISSUE THREAD

**Issue by Djoels** [lightly-ai/lightly#1453]
In MultiCropTransform used for SwaV method, length of crop size should be checked with length of crop_max_scales
In the code, crop_min_scales is checked twice, documentation is correct for the third check, but code isn't

https://github.com/lightly-ai/lightly/blob/7cf29706dd2e104a5dc809f0c6685dc35b080985/lightly/transforms/multi_crop_transform.py#L53

**Comment by guarin** [comment]
Thanks for the bug report! Made a PR to fix it :)
