### ISSUE TITLE
Additional field error in DatasourceConfigLOCAL instance

### ISSUE THREAD

**Issue by kais-bedioui** [lightly-ai/lightly#1463]
Hi,
I am just starting with Lightly and was following the tutorial in the docs.

When I run the data selection script on locally-stored data I encounter this error:
`
[2024-01-01 00:39:18] An unexpected exception occured: 
Error due to additional fields (not defined in DatasourceConfigLOCAL) in the input: {'id': '659209a705d3159533645f2c', 'purpose': 'INPUT', 'type': 'LOCAL', 'thumbSuffix': '.lightly/thumbnails/[filename]_thumb.[extension]', 'fullPath': 'lightly-input', 'webServerLocation': 'http://localhost:3456'}
`
What could be the issue?
Thanks

**Comment by guarin** [comment]
Hi! The error most likely happens because of the `fullPath` field in the config. This field is not expected for local configs as `relative_path` should be used instead. See our docs for more information: https://docs.lightly.ai/docs/local-storage#schedule-your-run

**Comment by japrescott** [comment]
Hey @kais-bedioui. Please ensure you are using the [latest lightly-worker version](https://docs.lightly.ai/docs/install-lightly#pull-and-update-the-lightly-worker-image) as local storage was shipped with version 2.9.x, while the latest stable version with many bugfixes is 2.10.2.

```
docker pull lightly/worker:latest
```

**Comment by kais-bedioui** [comment]
@japrescott I did the update, thanks for the heads up. I think @guarin 's input is what did it for me. Looking at that tutorial helped me know how to properly define the input paths.
This is solved.
