### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#1473]
This is just for people curious about why they can't use lightly with Python 3.12

The issue is that lightly uses PyTorch and there is not yet a stable release for Python 3.12. There is experimental support when you manually install the nightly build. You can read up more on that in the corresponding [PyTorch issue](https://github.com/pytorch/pytorch/issues/110436).

We expect support to be there sometime in Q1 2024.

**Comment by guarin** [comment]
Python 3.12 is now supported with PyTorch 2.2: https://github.com/pytorch/pytorch/issues/110436 although only as a preview. Most likely everything except torch compile already works.

Before supporting 3.12 officially we should also check if PyTorch Lightning has support: https://github.com/Lightning-AI/litgpt/issues/1210

**Comment by guarin** [comment]
Torch 2.4 is compatible with Python 3.12: https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix
