### ISSUE TITLE
Moco Memory bank example is error

### ISSUE THREAD

**Issue by ramdhan1989** [lightly-ai/lightly#1502]
Hi, 
I follow turotial for MoCo but I got this error
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18352\297540911.py in <module>
     29 model.to(device)
     30 
---> 31 criterion = NTXentLoss(memory_bank_size=(4096, 128))
     32 optimizer = torch.optim.SGD(model.parameters(), lr=0.06)

~\anaconda3\envs\myenv\lib\site-packages\lightly\loss\ntx_ent_loss.py in __init__(self, temperature, memory_bank_size, gather_distributed)
     56                  memory_bank_size: int = 0,
     57                  gather_distributed: bool = False):
---> 58         super(NTXentLoss, self).__init__(size=memory_bank_size)
     59         self.temperature = temperature
     60         self.gather_distributed = gather_distributed

~\anaconda3\envs\myenv\lib\site-packages\lightly\loss\memory_bank.py in __init__(self, size)
     42         super(MemoryBankModule, self).__init__()
     43 
---> 44         if size < 0:
     45             msg = f'Illegal memory bank size {size}, must be non-negative.'
     46             raise ValueError(msg)

TypeError: '<' not supported between instances of 'tuple' and `'int'``

**Comment by guarin** [comment]
Hi! Which version of lightly are you using? 

The `memory_bank_size` argument supports tuple arguments like `(4096, 128)` since v1.4.25. If you have an older version, please use `memory_bank_size=4096` instead.

**Comment by ramdhan1989** [comment]
well noted,
thank you

**Comment by guarin** [comment]
Closing this for now, let me know if you encounter any other issues :)
