### ISSUE TITLE
Fix examples on Windows

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1512]
We sometimes use lambdas in the examples when creating torch datasets: https://github.com/lightly-ai/lightly/blob/e7f13a53e68031ee0ae77124e76401b48381001f/examples/pytorch/mae.py#L87

This results in issues on Windows as lambdas cannot be pickled. We should update the examples and replace the lambdas with pickleable functions.

**Comment by guarin** [comment]
Yes, something like this should work:
```
def target_transform(t):
    return 0
```

**Comment by snehilchatterjee** [comment]
then I'd be happy to work on this. can you assign this issue to me ?
