### ISSUE TITLE
How to use lightly models on custom datasets

### ISSUE THREAD

**Issue by fereshtehforghani** [lightly-ai/lightly#1516]
I have a custom dataset that is inherited from datasets.ImageNet. Should I make this a LightlyDataset for my models to work? if yes how?

My dataset looks something like this:
`class MyDataset(datasets.ImageNet):`

**Comment by guarin** [comment]
Hi, you don't need a LightlyDataset, any torch dataset will work :)

**Comment by guarin** [comment]
I'll close this for now, please reopen or make a new issue if you have more questions.
