### ISSUE TITLE
Support latest `pydantic` version

### ISSUE THREAD

**Issue by ioangatop** [lightly-ai/lightly#1526]
Hi! is it possible to support the `pydantic` greater than 2? thank you!

**Comment by guarin** [comment]
Hi! Thanks for reporting the issue, we are looking into it!

**Comment by leokster** [comment]
Is there an update on this issue?

**Comment by guarin** [comment]
Hi, it should be available in the next release (1-2weeks)🤞🏼

**Comment by guarin** [comment]
Hi, just a heads up, the changes won't be included in todays release. We had a closer look and supporting pydantic v1 and v2 will require some bigger changes. Which features of lightly are you using? Pydantic is only used for the api client and if you don't need it it should be pretty easy to support v2 as well.

**Comment by ioangatop** [comment]
@guarin thanks a lot for addressing it, really appreciated 🙏
