### ISSUE TITLE
Tensorboard shut down as of 1 Jan 2024

### ISSUE THREAD

**Issue by hmf** [lightly-ai/lightly#1527]
Just to let you know that the [link](https://tensorboard.dev/experiment/2XsJe3Y4TWCQSzHyDFaPQA) in the ["Benchmarks" section](https://docs.lightly.ai/self-supervised-learning/getting_started/benchmarks.html#benchmarks) is broken.

**Comment by guarin** [comment]
Hi! Thanks for reporting the issue. We are looking into alternatives for `tensorboard.dev` (issue is here #1435). In the meantime I'll probably just replace the links to directly download the tensorboard logs so you can visualize them locally. Would this work for you?

**Comment by hmf** [comment]
Yes, direct ins are ok. Not a problem with me. 

Thank you.
