### ISSUE TITLE
Adding Custom Transform

### ISSUE THREAD

**Issue by CharisWg** [lightly-ai/lightly#1588]
I added A_transform.py to lightly/lightly/transforms/A_transform.py and included the following import statement in lightly/lightly/transforms/__init__.py: from lightly.transforms.A_transform import ATransform, AViewTransform

Despite this, I encountered the following error:
ModuleNotFoundError: No module named 'lightly.transforms.A_transform'

**Comment by guarin** [comment]
Hi! How did you install lightly?

If you clone the repository and modify files in it make sure to install it like this:
```
pip install -e path/to/lightly/directory
```

Then all changes to the repository should be reflected in your virtual environment.

**Comment by CharisWg** [comment]
Thanks! After running pip install -e path/to/lightly/directory, I encountered the following errors:
ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\users\\localadmin\\anaconda3\\envs\\sslyolov8\\lib\\site-packages\\lightly\\transforms'
Consider using the `--user` option or check the permissions.

**Comment by guarin** [comment]
Hi, this looks like an issue with Anaconda on Windows and is unrelated to the lightly package, please see: https://stackoverflow.com/questions/53519380/permissionerror-cannot-access-the-file-because-it-is-being-used-by-another-pro

**Comment by CharisWg** [comment]
fixed it.Thanks
