### ISSUE TITLE
I really need the code for downstream segmentation tasks using MAE pre-training weights

### ISSUE THREAD

**Issue by rodmarn** [lightly-ai/lightly#1591]

**Comment by guarin** [comment]
Hi! We sadly don't have example code for segmentation finetuning using MAE. AFAIK this code was also not published in the original MAE repo. The paper states that for segmentation the code from https://github.com/microsoft/unilm/tree/master/beit was used.

May I ask what your use-case is? Are you looking to finetune MAE using a specific segmentation library or are you interested in reproducing the results from the paper?

**Comment by guarin** [comment]
Will close this for now, please reopen if you have more questions.
