### ISSUE TITLE
Multi-crop in SimCLRTransform

### ISSUE THREAD

**Issue by opencomvis** [lightly-ai/lightly#1639]
Some models in **lightly** used **SimCLRTransform** (e.g, DCL, NNCLR); however, these models also employ the idea of multi-crop (that's originally used for SwaV model) to improve their results, as mentioned in their papers. Is there a way to use multi-crop in **SimCLRTransform**? 
Thank you for your help.

**Comment by philippmwirth** [comment]
Hi @opencomvis, thanks for the question! At the moment we don't offer out-of-the-box multi-crop versions of the SimCLR or DCL loss function but it should be possible to build them based on our pairwise contrastive loss implementations.

For the augmentations you can combine [MultiCropTransform](https://github.com/lightly-ai/lightly/blob/master/lightly/transforms/multi_crop_transform.py) with custom transforms or simply use [SwAV transform](https://github.com/lightly-ai/lightly/blob/master/lightly/transforms/swav_transform.py).

**Comment by opencomvis** [comment]
Got it, thank you for the response.
