### ISSUE TITLE
outdated conda build

### ISSUE THREAD

**Issue by 0x1orz** [lightly-ai/lightly#1640]
The latest release of the conda-forge channel is 1.5.6. Respectively, are there plans to update thanks.

**Comment by guarin** [comment]
Hi, thanks for the issue, we are aware and will try to update it shortly. If you would like to help out please feel free to submit a PR to the conda feedstock to update the latest dependencies: https://github.com/conda-forge/lightly-feedstock/pulls

See also:
* https://github.com/conda-forge/lightly-feedstock/issues/20
* https://github.com/lightly-ai/lightly/issues/1558

**Comment by guarin** [comment]
The builds should now be updated :) You can find new releases here: https://anaconda.org/conda-forge/lightly
Please let me know if you encounter any issues.
