### ISSUE TITLE
Add IRFFT2 transform

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1656]
See https://github.com/lightly-ai/lightly/issues/1646 for information

Please use https://pytorch.org/docs/stable/generated/torch.fft.irfft2.html to implement the transform.

**Comment by snehilchatterjee** [comment]
Hi, I'd like to work on this as my first issue!

**Comment by guarin** [comment]
Hi, yes of course, I'll assign the issue to you.

**Comment by snehilchatterjee** [comment]
Hi, I’ve added the `RFFT2D` and `IRFFT2D` transforms to `lightly/transforms`. As mentioned in the original issue, I ensured that the input and output formats for both transforms are `C, H, W`. 

Additionally, I used an image from the BSD100 dataset to verify that the transforms are working as expected. I obtained the frequency image using `RFFT2D` and passed it through `IRFFT2D` to confirm that the original image is restored correctly.

Is there anything else I might have missed in addressing the issue? If everything is in order, would it be alright to open a PR for these two transforms?

**Comment by guarin** [comment]
This sounds great! Feel free to open a PR

**Comment by snehilchatterjee** [comment]
Hi have opened a PR but it seems that it failed on format check because of __init__.py because I didn't want to change the format of the file from the master branch. Please let me know if you want me to change the format for __init__.py so that it passes the format check.

**Comment by guarin** [comment]
I answered directly in the PR :)
