### ISSUE TITLE
Fixing Docs Layout.

### ISSUE THREAD

**Issue by sanketshinde3001** [lightly-ai/lightly#1669]
![image](https://github.com/user-attachments/assets/eb3ff620-92aa-49eb-b763-3a291a80eb4e)

Docs look un even on big screen. i'll make it center.

**Comment by guarin** [comment]
Hi and thanks for creating the issue! Is there a particular reason why you would prefer it to be centered? As far as I know the default for the Read The Docs theme is that it is left aligned. E.g. the Read The Docs docs are also left aligned: https://docs.readthedocs.io/en/stable/

**Comment by sanketshinde3001** [comment]
Hi @guarin , My main concern is that on larger screens, the left alignment can make the content feel a bit uneven. Centering it might enhance readability and provide a more balanced look, but I completely understand if sticking with the default is preferred.

**Comment by guarin** [comment]
I completely agree that the left alignment doesn't look good on large screens. If there is an easy config option to center it I would consider switching but if it is more effort I would prefer to keep the default. We are also considering switching to a completely new theme in the future, but this will take a while.

**Comment by sanketshinde3001** [comment]
Ohk NP. 😊

**Comment by Abhrajitdas02** [comment]
Hi, can you assign this issue to me?

**Comment by guarin** [comment]
Thanks for your interest @Abhrajitdas02 but it is not yet clear if we want to implement this.
