### ISSUE TITLE
Cleanup docstrings in lightly/loss subpackage.

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#1673]
See #1216 for information

**Comment by ayush22iitbhu** [comment]
@guarin please assign it to me

**Comment by Aienthu1** [comment]
@guarin please assign me this issue.

**Comment by guarin** [comment]
@ayush22iitbhu did you already have time to work on this?

**Comment by ayush22iitbhu** [comment]
@guarin yes I am working on this. It will be done soon.

**Comment by ayush22iitbhu** [comment]
@guarin I'll submit the PR before tomorrow EOD.

**Comment by ayush22iitbhu** [comment]
@guarin review PR.
