### ISSUE TITLE
ApiWorkflowClient.sampling(): check if tag_name already exists

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#169]
The name in the sampler_config is used as the name of the new tag created after the sampling. There must not be a tag with that name already in the database. Otherwise an error occurs in the queueworker after a sampling is performed. 

This error is shown in the queueworker as
```
Error: {"status":400,"statusText":"Bad Request","url":"https://api-dev.lightly.ai/v1/datasets/603e008523de290032d7b9c4/tags?token=347f1dfbc3879a142d536d0b","size":0,"body":{"code":"TAG_NAME_EXISTS","error":"TAG_NAME_EXISTS"},"headers":{"content-type":["application/json; charset=utf-8"],"access-control-allow-origin":["*"],"etag":["W/\"41-ZHM/mN4+VRsqQFOimQGdZ/6FSbE\""],"vary":["Accept-Encoding"],"x-cloud-trace-context":["086bb37ac3f1bd91fe40e19e6457f11a"],"date":["Tue, 02 Mar 2021 11:50:57 GMT"],"server":["Google Frontend"],"content-length":["65"],"connection":["close"]}}
```
## Solution on Pip side
Instead, it could be checked at the start of a sampling whether this tag already exists. There are the following possible options to handle such a case:
1. Throw an Exception.
2. Warn the user and skip the sampling.
3. Warn the user, and generate a new sampling name by appending a counter, similar to this code for filenames
```python
def uniquify(path):
    filename, extension = os.path.splitext(path)
    counter = 1

    while os.path.exists(path):
        path = filename + " (" + str(counter) + ")" + extension
        counter += 1

    return path
```
Disadvantages:
- race conditions: What happens if a tag is created on the server side during the sampling?
- before every sampling, all tags (and thus all bitmasks) have to be downloaded.

## Solution on api side:
If the tag_name already exists, add a counter to it, similar to solution 3 on the pip side.
Disadvantage: still chance of race conditions, but much less likely.

**Comment by philippmwirth** [comment]
I'd suggest to handle it as follows:
- The pip package checks whether a tag with the name already exists (if this becomes to slow we can add an endpoint to only return the tag-names & ids).
- If it doesn't exist it submits the job.
- If the user creates a tag with the same name in the meantime on the web-app the job will fail.
- The error message in the PIP package for this case should be very clear & precise.

I'd love something like this: 
``` 
SamplingErrorTagExists: Sampling job failed because tag with name tag-name already exists. See docs.lightly.ai/lightly.api.html#module-lightly.api.errors
```
Where `SamplingErrorTagExists` is defined in `lightly.api.errors`.

However, for starters, I'd just do it like this:
```
RuntimeError: Sampling job failed because tag with name tag-name already exists.
```
