### ISSUE TITLE
Dino embedding inference

### ISSUE THREAD

**Issue by JAVARSHA** [lightly-ai/lightly#1713]
I finetuned dino on my dataset:

```
class DINO(torch.nn.Module):
    def __init__(self, backbone, input_dim):
        super().__init__()
        self.student_backbone = backbone
        self.student_head = DINOProjectionHead(
            input_dim, 512, 64, 768, freeze_last_layer=1
        )
        self.teacher_backbone = copy.deepcopy(backbone)
        self.teacher_head = DINOProjectionHead(input_dim, 512, 64, 768)
        deactivate_requires_grad(self.teacher_backbone)
        deactivate_requires_grad(self.teacher_head)

    def forward(self, x):
        y = self.student_backbone(x).flatten(start_dim=1)
        z = self.student_head(y)
        return z

    def forward_teacher(self, x):
        y = self.teacher_backbone(x).flatten(start_dim=1)
        z = self.teacher_head(y)
        return z

backbone = torch.hub.load('facebookresearch/dino:main', 'dino_vitb16', pretrained=True)
input_dim = backbone.embed_dim

model = DINO(backbone, input_dim)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

transform = DINOTransform()

def target_transform(t):
    return 0

dataset = LightlyDataset("/content/drive/MyDrive/dataset", transform=transform)

collate_fn = MultiViewCollate()

dataloader = torch.utils.data.DataLoader(
    dataset,
    batch_size=8,
    shuffle=True,
    drop_last=True,
    num_workers=2,
    collate_fn=collate_fn,
)

criterion = DINOLoss(
    output_dim=768,
    warmup_teacher_temp_epochs=5,
)

criterion = criterion.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
```

I've saved the model as a .pth file in my drive. Now how do I get embeddings for an image using this finetuned model

**Comment by JAVARSHA** [comment]
@guarin @philippmwirth @IgorSusmelj @japrescott @shaundaley39 @MalteEbner

**Comment by guarin** [comment]
You want to use the `backbone` for embedding creation. After training you can save it with:
```
torch.save(backbone.state_dict(), "backbone.pth")
```

If you already saved your model with:
```
torch.save(model.state_dict(), "model.pth")
```
the easiest way to load it again is to run:
```
class DINO(torch.nn.Module):
    def __init__(self, backbone, input_dim):
        super().__init__()
        self.student_backbone = backbone
        self.student_head = DINOProjectionHead(
            input_dim, 512, 64, 768, freeze_last_layer=1
        )
        self.teacher_backbone = copy.deepcopy(backbone)
        self.teacher_head = DINOProjectionHead(input_dim, 512, 64, 768)
        deactivate_requires_grad(self.teacher_backbone)
        deactivate_requires_grad(self.teacher_head)

    def forward(self, x):
        y = self.student_backbone(x).flatten(start_dim=1)
        z = self.student_head(y)
        return z

    def forward_teacher(self, x):
        y = self.teacher_backbone(x).flatten(start_dim=1)
        z = self.teacher_head(y)
        return z

backbone = torch.hub.load('facebookresearch/dino:main', 'dino_vitb16', pretrained=True)
input_dim = backbone.embed_dim

model = DINO(backbone, input_dim)
model.load_state_dict(torch.load("model.pth", weights_only=True))
```

Now `backbone` contains the weights you want. You can save the backbone for easier access in the future:
```
torch.save(backbone.state_dict(), "backbone.pth")
```

**Comment by guarin** [comment]
> hey but I've finetuned dino on my dataset using lightlydataset, now can I load it like this:
> ```
> backbone = torch.hub.load('facebookresearch/dino:main', 'dino_vitb16', pretrained=True)
> input_dim = backbone.embed_dim
> 
> model = DINO(backbone, input_dim)
> 
> model_save_path = "/content/drive/MyDrive/Lightly/50-dino.pth"
> model.load_state_dict(torch.load(model_save_path))
> 
> device = "cuda" if torch.cuda.is_available() else "cpu"
> model.to(device)
> model.eval()
> ```

Yes, as long as you use the `backbone` when creating the embeddings everything is all right :)

> Also about the inference, what transform shd I use to get the embedding:

The proposed transforms look good for embedding.

**Comment by JAVARSHA** [comment]
Hey @guarin. Can you suggest other inference methods to get embeddings from dino. Cause my images are of varying sizes (i.e. some are squares rectangles (with either l > b or b> l both cases). I think center crop is cutting a lot of detail and maybe that's why the similarity search results are bad

**Comment by guarin** [comment]
You can remove the `CenterCrop` and use `Resize` only: `Resize(size=(224, 224))`. This will distort the images a bit but nothing is cropped and you don't get black borders if height != width.
