### ISSUE TITLE
Add subset from filenames functionality to LightlyDataset

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#175]
The `ActiveLearningAgent` returns a list of filenames for which the user will need to get predictions. Since this can be difficult and it's important, that the order of the filenames stays the same, it would be a good option to add the following functionality to the `LightlyDataset`.

```python
dataset = LightlyDataset.subset_from_filenames(input_dir, agent.unlabeled_set)
dataloader = torch.utils.data.DataLoader(dataset, shuffle=False, batch_size=1)
```

## Question A: Which kind of base dataset are supported during the creation?

1. input_dir: `str`
2. dataset: `torchvision.datasets.ImageFolder`
3. dataset: `lightly.data._helpers.DatasetFolder`
4. dataset: `lightly.data._video.VideoDataset`
5. dataset: `generic torchvision dataset` - Problem: it does not necessarily contain filenames
6. dataset: `LightlyDataset`

## Question B: How is the `SubsetDataset` represented:

1. just like the base dataset - not compatible with Option A1
2. a `LightlyDataset`
3. a `LightlyDatasetSubset`

## Question C: How is the `SubsetDataset` created:

1. Add a method to the base dataset - only compatible with option A6
2. Add a constructor to its representation - only compatible with B2 and B3

**Comment by philippmwirth** [comment]
The following snippet could then be added to the introduction about active learning in the docs:

```python
@torch.no_grad()
def get_predictions_by_filenames_in_order(input_dir: str,
                                          agent: ActiveLearningAgent,
                                          model: torch.nn.module):
    """

    """
    transform = torchvision.transforms.ToTensor()
    dataset = LightlyDataset.subset_from_filenames(
        input_dir, agent.unlabeled_set, transform=transform
    )
    dataloader = torch.utils.data.DataLoader(dataset, shuffle=False, batch_size=1)

    predictions = []
    for img, _, filename in dataloader:
        output = model(img).detach()
        predictions.append(output.squeeze().cpu().numpy())

    return np.array(predictions)
```

**Comment by philippmwirth** [comment]
An alternative solution would be to add a function like this:

```Python
dataset = LightlyDataset(input_dir)
unlabeled_set = dataset.to_subset_by_filenames(agent.unlabeled_set)
```

This function would be much easier to implement. The disadvantage is that the user will have to work on a PyTorch `Subset` instead of a `LightlyDataset`.

**Comment by MalteEbner** [comment]
We could also create a class `LightlyDatasetSubset` which is created from a `LightlyDataset` and a `list of filenames` and is a drop-in replacement for a `LightlyDataset` by possibly inheriting from it.

**Comment by philippmwirth** [comment]
I like this idea. Let's go with that. Preferrably name it `LightlySubset`.
