### ISSUE TITLE
Add batch shuffling to MoCo

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#18]
In their paper, the authors of MoCo mention that they shuffle their batches in order to prevent a flow of information between the key encoder and the query encoder (if the positive pairs are normed with the same statistics, the model can cheat). As a solution, they shuffle the batches and split them into smaller sub-batches on which the batch norm is then calculated. We can and should implement a similar strategy.

**Comment by philippmwirth** [comment]
Just a sneak peek on how shuffling the batches can improve the test accuracy. 

**MoCo with a ResNet18 on Cifar-10**
orange: w/o shuffling, 200 epochs
light blue: w/ shuffling, 100 epochs
![grafik](https://user-images.githubusercontent.com/65946090/97567371-019ae400-19e7-11eb-927e-7df52612c64d.png)

**Comment by IgorSusmelj** [comment]
Awesome. Plots are from lightly already?

**Comment by philippmwirth** [comment]
> 
> 
> Awesome. Plots are from lightly already?

Yes, I have implemented a protoype.
