### ISSUE TITLE
Add Google Colab link for active-learning tutorial

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#192]
To make it easier for someone to try out the active-learning tutorial I would propose to make it available as a Google Colab Notebook.
The goal is that the user only has to provide the `token` and the `datasetId`. Everything else can be run and the tutorial runs through.

**Comment by MalteEbner** [comment]
We could even let a new dataset be created from the pip package, then the user would not even need to provide a `dataset_id`.

**Comment by IgorSusmelj** [comment]
I added a google colab link to the tutorial (at the beginning of it). We can modify the colab ourselves. If anyone else wants access drop me a message.
