### ISSUE TITLE
Add correctness check before uploading samples and embeddings

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#206]
When uploading a dataset using lightly-upload where the embeddings are not in the right csv format the CLI should break before uploading part of the data.

E.g. when one of the columns has the wrong name: 
![image](https://user-images.githubusercontent.com/1522766/110758642-0604c280-824d-11eb-97d3-c1d295800572.png)

Furthermore, we should make sure that we don't upload embedding files that don't match our specs.

**Comment by MalteEbner** [comment]
We already make sure that we don't upload embedding files not matching the specs, as they cause the reordering according to the mapping to fail: https://github.com/lightly-ai/lightly/blob/e6565c0cd58e17472841a16943c360266de212a2/lightly/api/api_workflow_upload_embeddings.py#L72-L85

**Comment by guarin** [comment]
Upload is deprecated.
