### ISSUE TITLE
Add Barlow Twins

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#211]
There is a new paper from Facebook AI called **Barlow Twins: Self-Supervised Learning via Redundancy Reduction**

Let's add the model to lightly :)

We have a (not perfect yet) running version here: https://github.com/IgorSusmelj/barlowtwins

We could use this one as a starting point. There are different option of adding the model. 
- We could add a wrapper BarlowTwins (just as we did with SimSiam or SimCLR models) which uses a similar model to SimSiam. Maybe it even instantiates a SimSiam model in the back!?
- Add the loss function from cross-correlation

**Comment by AdrianArnaiz** [comment]
Hi! I am really interested in working on this issue. If you agree, I'll be forking the repo from next Monday and humbly contributing on this topic. @IgorSusmelj

* [Paper](https://arxiv.org/abs/2103.03230)
* [Igor Susmelj repo](https://github.com/IgorSusmelj/barlowtwins)
* [Official FB repo (*currently empty*)](https://github.com/facebookresearch/barlowtwins)

**Comment by philippmwirth** [comment]
Hi and welcome on board! :) We would be excited to see you working on this issue.

Let me know if you have any questions or if you get stuck somewhere. I'm happy to help.
You can post in the "dev" channel on our [discord](https://discord.com/invite/xvNJW94) or also write me a direct message there.

Ping me once you have forked the repo then I'll assign the issue to you.
