### ISSUE TITLE
Update requirements list

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#219]
We have quite some new requirements. (see https://github.com/lightly-ai/lightly/blob/develop/requirements/base.txt)
Let's figure out whether we need all of them.

- Check if some of the dependencies require each other (so we don't have to include both)
- Check if we really need some of the dependencies
- The fewer requirements the better :)

- [ ] Update requirements/base.txt
- [ ] Update readme and wherever we mention the dependencies

**Comment by IgorSusmelj** [comment]
I'm pretty sure we can drop urllib3 and setuptools

**Comment by MalteEbner** [comment]
`urllib3` and `setuptools` are needed by the generated code, together with `certifi`, `six` and `python_dateutil`. Once we also have the docker code and the upload to a url migrated, we can drop  `requests` instead.

**Comment by IgorSusmelj** [comment]
> `urllib3` and `setuptools` are needed by the generated code, together with `certifi`, `six` and `python_dateutil`. Once we also have the docker code and the upload to a url migrated, we can drop `requests` instead.

Could you point me to the code which requires setuptools in the generated code? For me it doesn't make sense. Setuptools is for creating the package. We use it for distribution. Could it be that you mean that we use setuptools to generate the generated code? But to actually run it we don't need it?

running grep on the full repo for `setuptools` returns the following:
```
(lightly) igor_lightly_ai$ grep -rnw lightly/ -e setuptools
lightly/requirements/base.txt:12:setuptools >= 21.0.0
lightly/tox.ini:18:#    Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (40.6.2)
lightly/tox.ini:88:           pip install setuptools==21.0.0
lightly/lightly/openapi_generated/requirements.txt:4:setuptools >= 21.0.0
lightly/setup.py:1:import setuptools
lightly/setup.py:128:    setuptools.setup(
```

**Comment by guarin** [comment]
Requirements have been updated in the meantime
