### ISSUE TITLE
Add information about how to use custom datasets with lightly

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#231]
From the documentation, it is not yet fully clear how to use lightly with a custom dataset and dataloader.

I would add the following:
- add to the docstring of the LightlyDataset how we could build a custom dataset (e.g. it just has to return tensor, label and filename
- add more detailed information with an example to the tutorial (https://docs.lightly.ai/tutorials/structure_your_input.html) how to use custom datasets

**Comment by guarin** [comment]
This has been addressed in https://github.com/lightly-ai/lightly/pull/1569
