### ISSUE TITLE
Add Alignment and Uniformity Loss

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#250]
# Add Alignment and Uniformity Loss
Following the discussion in #249 and as suggested by @EelcoHoogendoorn.

Implement the loss function described [here](https://arxiv.org/abs/2005.10242), which achieves competitive results with more cited ones (symmetric negative cosine similarity & contrastive loss) while providing better interpretability.

**Comment by EelcoHoogendoorn** [comment]
Thanks for facilitating this; ive made a fork on my account and made a feature branch there branching from dev. Any further details on how youd like to work towards a PR?

**Comment by philippmwirth** [comment]
Since there are no dependencies with this issue, you can simply create a PR once you feel comfortable with your implementation and then we'll take a look. It would be good to rebase your feature branch onto our develop before you open the PR. 

If you have any questions just let us know :)
