### ISSUE TITLE
Discuss: How to handle different bounding box formats?

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#253]
When working with bounding boxes there are several formats people work with.
We can specify the coordinates (x1, y1, x2, y2) or (x1, y1, w, h) or others. The same for the scale of the box coordinates (between 0 and 1.0) or (0 to image width and height).
Let's discuss whether we want to provide any helper functions/ classes to ease the use of the different formats for the user.

**Proposals we have so far:** 

- Bounding Box Class for each type of possible bbox and all provide the necessary functions for our scorer.
- Scorer Class for each type of possible bbox and all calculate the scores they can
- Helper functions which make it easy for the user to switch between formats

**Comment by MalteEbner** [comment]
Creating a class for the model output (copied from #252):
I would specify each element of model_output not only in comments, but also more precisely in code using a simple class:
```python
class ImageObjectDetection_nameTBD:
    def __init__(self,
                 boxes: List[List[int]],
                 object_probabilities: List[float],
                 class_probabilities: List[List[float]]
                 ):
        if len(boxes) != len(object_probabilities) or len(object_probabilities) != len(class_probabilities):
            raise ValueError(f"All arguments must have the same length, but "
                             f"len(boxes)=={len(boxes)}, "
                             f"len(object_probabilites)=={len(object_probabilities)}"
                             f"and len(class_probabilities)=={len(class_probabilities)}")
        len_first_box = len(boxes[0])
        if len_first_box != 4:
            raise ValueError(f"Each box must have 4 values, but only {len_first_box} were provided.")
        self.boxes = boxes
        self.object_probabilities = object_probabilities
        self.class_probabilities = class_probabilities
```
Having it in a class has the following advantages:
- allows checking of the required types and format
- the format is not only documented in comments but directly as type hints, see screenshot
- the names of the three properties are explicitly typed preventing typos like "object_probabailities"
<img width="474" alt="Screenshot 2021-03-19 at 19 38 10" src="https://user-images.githubusercontent.com/20324507/111827889-bc6e4480-88ea-11eb-8857-f9e562321d75.png">

**Comment by philippmwirth** [comment]
So you're in favor of option 1 listed in @IgorSusmelj description?

**Comment by IgorSusmelj** [comment]
Hmm, @MalteEbner, what you propose helps to prevent errors. But it doesn't solve the problem of dealing with different formats. I feel this is less of a problem than making it easy to work with different bounding box formats. I would focus first on the problem of how to work with different formats and whether we want to provide help for the conversion.

**Comment by MalteEbner** [comment]
For the bounding boxes, I would create one class with different constructors for different formats. However, all constructors should save the values in one single format, so that the calculation of scores is decoupled from the format of bounding boxes:
```python
class BoundingBox:
    def __init__(self, x1: Union[int, float], y1: Union[int, float], x2: Union[int, float], y2: Union[int, float], 
                 image_width: int, image_height: int):
        if isinstance(x1, float):
            x1 = x1 * image_width
        # the same for y1, x2, y2
        self.x1 = x1
        self.y1 = y1
        self.x2 = x2,
        self.y2 = y2,
        self.image_width = image_width
        self.image_height = image_height

    @classmethod
    def from_x_y_w_h(cls, x: Union[int, float], y: Union[int, float], w: Union[int, float], h: Union[int, float]):
        return cls(x, y, x + w, y + h)
```

**Comment by IgorSusmelj** [comment]
I'm not a fan of this approach. This would bloat the repo just to deal with different formats. And still, we wouldn't capture all of them. There are also many custom formats. E.g. there was the series of centernet/ cornernet papers where they output the center of the bounding box: https://towardsdatascience.com/centernet-keypoint-triplets-for-object-detection-review-a314a8e4d4b0
