### ISSUE TITLE
CLI of lightly: allow setting the output file

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#280]
Some commands create output files which are the main result of them and are used in later steps. As their location is not specified, it is need to find the created file afterwards, write down its path and then use it in the next step. Instead, it would be great, if I could specify where the file should be saved.

- lightly-train: `checkpoint.ckpt`
- lightly-embed: `embeddings.csv`

Tasks:

- [ ] adapt the `lightly-train`to set the checkpoint filename
- [ ] adapt the `lightly-embed `to set the embeddings filename

It should be possible to do the following:
```bash
CHECKPOINT_FILENAME="checkpoint_1.ckpt"
EMBEDDINGS_FILENAME="embeddings_1.csv"
lightly-train input_dir=cat checkpoint=$CHECKPOINT_FILENAME
lightly-embed input_dir=cat checkpoint=$CHECKPOINT_FILENAME embeddings=$EMBEDDINGS_FILENAME
lightly-upload input_dir=cat embeddings=$EMBEDDINGS_FILENAME token=your_token dataset_id=your_dataset_id
```
Thus the lightly-magic command could be split into three separate commands without needing to look up the names of the generated files.

**Comment by philippmwirth** [comment]
You can set the working directory to whatever you want with `hydra.run.dir=my/working/dir`. 

The problem I see with your approach is that the command `lightly-magic` produces two files: the checkpoint file and the embeddings file.

**Comment by MalteEbner** [comment]
>>>The problem I see with your approach is that the command lightly-magic produces two files: the checkpoint file and the embeddings file.

I agree, I did not think about that. We should have separate arguments/filenames for the CLI commands. I adapted the issue accordingly.

**Comment by philippmwirth** [comment]
ok, I like the idea of reusing the `embeddings` argument for output/input paths. However, it doesn't work for the checkpoint because the checkpoint is also an input argument for `lightly-train` (e.g. continue training). Furthermore, we would need to solve the following question: Is the filename relative to the calling directory or the working directory of lightly?

**Comment by MalteEbner** [comment]
> `lightly-train` has a checkpoint and input and output
We could solve this by renaming to `checkpoint_out` and `embeddings_out` or similar terms.
> relative positioning of filenames:
We should do it the same as for the other filenames, i.e. `../embeddings.csv` should point to the same file both for `lightly-embed` (as output) and `lightly-upload` (as input)
