### ISSUE TITLE
Add tutorial for active learning for object detection with Lightly

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#284]
Idea is to implement a simple walk-through tutorial to train an object detection model using active learning with the Lightly platform. I currently think about using either [Detectron 2](https://github.com/facebookresearch/detectron2) or [Yolov5](https://github.com/ultralytics/yolov5) as a model framework.

**Comment by philippmwirth** [comment]
Maybe not Yolov5, remember the problems we had due to preprocessing of the images?

**Comment by IgorSusmelj** [comment]
Will start with detectron 2 and then do another one for yolo

**Comment by IgorSusmelj** [comment]
What do you think about creating a tutorial similar to this one: https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=ZyAvNCJMmvFF

I would follow a similar workflow but focus on showing how to use detectron2 with active learning.

**Comment by IgorSusmelj** [comment]
Quick update on the issue. I will make a tutorial on how to fine-tune an object detection model from detectron2 on comma10k for the detection of cars.
The tutorial will cover all aspects of a real-world scenario many ML engineers are facing:
- We leverage a pre-trained model using transfer learning to improve detection for our specific use case (autonomous driving)
- We use active learning to select the images where our model performs poorly
- We show how lightly can be used for AL and visualization of the dataset
