### ISSUE TITLE
How to use Pretrained SimCLR model to get image imbedding?

### ISSUE THREAD

**Issue by Ashufet** [lightly-ai/lightly#288]

**Comment by IgorSusmelj** [comment]
Hi @Ashufet,

could you please elaborate more on your question? The example [here](https://github.com/lightly-ai/lightly/issues/287#issuecomment-818971750) shows in the last lines of code how to get the embedding of a pretrained model.

**Comment by Ashufet** [comment]
I just wanted to know how can we use the pre-trained SimCLR model which was trained on some large data while doing the benchmarking. Pretrained model on CIFAR data or some other data.

Currently, the example you are referring is in that I am training a blank model on new dataset.

**Comment by philippmwirth** [comment]
Hi @Ashufet, thanks for the question. It is indeed poorly documented how you can do that.

For an overview of the different checkpoints we provide, please see our [model zoo](https://github.com/lightly-ai/lightly/blob/13d3e5bc7ef9ba70b9f815f48811a6ff0fb89249/lightly/models/zoo.py#L8).

You can pick a url from the zoo and then use `lightly.cli._helpers.load_state_dict_from_url` ([this one](https://github.com/lightly-ai/lightly/blob/13d3e5bc7ef9ba70b9f815f48811a6ff0fb89249/lightly/cli/_helpers.py#L45)) to get the state dict.

If you have trouble getting it to work, you can check out how we do it in `lightly.cli.embed.py`.

I hope this helps :) let us konw if you have any further questions.
