### ISSUE TITLE
loader.num_workers=12 doesn't actually spawn multiple workers

### ISSUE THREAD

**Issue by japrescott** [lightly-ai/lightly#295]
I've noticed that when trying to create an embedding with the param `loader.num_workers` there seems to be no difference in CPU consumption;
`lightly-embed input_dir='./75000' trainer.max_epochs=1 loader.num_workers=12`

This could be that my images are ~8kb and there is some other bottleneck preventing the CPUs to max-out? in My ActivityMonitor (macOSX) I see that I have 80% idle CPU

System: MacBook Pro (16-inch, 2019), 2.6 GHz 6-Core Intel Core i7
OS: MacOSX 11.2.3

**Comment by japrescott** [comment]
also, using `lightly-upload token='asdad' dataset_id='asdasd' input_dir=./75000 loader.batch_size=64 loader.num_workers=12` doesnt actually spawn 12, but it reports that it spawn 8 workers.

**Comment by MalteEbner** [comment]
@japrescott You are right, the function
https://github.com/lightly-ai/lightly/blob/fc50052f9b2dc62dad9e4823783a471c17c58831/lightly/api/api_workflow_upload_dataset.py#L17-L18 is called without specifying the workers when calling it from
https://github.com/lightly-ai/lightly/blob/fc50052f9b2dc62dad9e4823783a471c17c58831/lightly/cli/upload_cli.py#L51-L56
