### ISSUE TITLE
Model Zoo is PreTrained on ImageNet or CIFAR10?

### ISSUE THREAD

**Issue by beluis3d** [lightly-ai/lightly#297]
I'm not sure which dataset it's pretrained on. The paper mostly uses ImageNet, but Lightly seems to use CIFAR10 examples mostly. Either way, I'm not sure.

**Comment by IgorSusmelj** [comment]
Hi @beluis3d, for the current model zoo we used a custom dataset. The models have been trained on 64x64 pixel input images for 100 epochs. We do not recommend using them as a baseline but as a starting point for fine-tuning the SSL models on your dataset. 

The Lightly ResNet architecture also slightly differs from the torchvision ResNet (see https://docs.lightly.ai/getting_started/advanced.html#models). There is an issue in place and we will likely switch by default to the torchvision backbones (see https://github.com/lightly-ai/lightly/issues/62).

We use cifar10 for benchmarking. The benchmarks run fast and allow us to quickly check whether the models run properly. There have also been suggestions to start benchmarking on Imagenette (see https://github.com/lightly-ai/lightly/issues/279). 
We will start ImageNet benchmarks later this year.
