### ISSUE TITLE
Allow creation of dataset during upload

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#299]
At the moment a user of the Lightly Platform would need to go to the webapp and create a new dataset to get the `dataset_id` for uploading. However, it would be great if the user could just use the token and during the upload process, a new dataset would automatically be created.

**Comment by philippmwirth** [comment]
A user can already create datasets from the pip package, see [this](https://github.com/lightly-ai/lightly/blob/develop/lightly/api/api_workflow_datasets.py).

**Comment by philippmwirth** [comment]
Do you mean from the command line?

**Comment by IgorSusmelj** [comment]
> A user can already create datasets from the pip package, see [this](https://github.com/lightly-ai/lightly/blob/develop/lightly/api/api_workflow_datasets.py).

How does the user know about this? Is it mentioned anywhere in the docs? 

Yes, I would also add this option to the CLI as I think the CLI is the main interface between the pip package and the platform.
