### ISSUE TITLE
Self supervised models don't work with batch size = 1

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#307]
All self supervised models  apply currently a squeeze operation after passing an input batch through the backbone:
https://github.com/lightly-ai/lightly/blob/bd982c9513effd75c11d9b2671de09a4be6ce155/lightly/models/simclr.py#L94

But this breaks the batch structure if you have batch size = 1 as the batch dimension is removed. A possible fix for it is to replace squeeze with flatten as it takes a start dimension argument:
```
f0 = self.backbone(x0).flatten(start_dim=1)
```

**Comment by philippmwirth** [comment]
Closed by #372
