### ISSUE TITLE
Restructure config files

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#31]
Currently, all CLI configs are stored in a single file `config.yaml`. In the future, the file structure should look as follows:
```
config/
|-- config.yaml
|-- model/
   |-- resnet-18.yaml
   |-- resnet-34.yaml
   |-- ...
|-- data/
  |-- data.yaml
|-- ...
```

This way, a user can still overwrite the default arguments like so:
```bash
lightly-train input_dir=my-dir model.num_ftrs=32
```
However, one could easily switch between different default settings and even write custom config files
```
# this will use the default settings from resnet-34.yaml
lightly-train input_dir=my-dir model=resnet-34 
# this will use the settings in the custom config file
lightly-train input_dir=my-dir model=my-model
```

**Comment by guarin** [comment]
Not planned for now.
