### ISSUE TITLE
Momentum Update in Eval Mode

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#322]
Momentum update is currently performed regardless of the train/eval mode of the model at the beginning of each forward pass. See:
https://github.com/lightly-ai/lightly/blob/7314e93077d11fc905c4a5152ad2ab4663122b22/lightly/models/moco.py#L106

This can be an issue if you have validation runs during training.

**Comment by philippmwirth** [comment]
This should be handled by #494 and the deprecation of the high-level implementations in `1.2.0`.
