### ISSUE TITLE
Return the dataset_id when creating a new dataset through the CLI

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#332]
When using the lightly CLI to upload a new dataset it would be great to return the `dataset_id` of the newly created dataset.

Otherwise, the user has to go to the web app to get the `dataset_id`.

Also make sure that embedding path and checkpoint path are still printed.

**Comment by philippmwirth** [comment]
See: https://github.com/lightly-ai/lightly/issues/310
