### ISSUE TITLE
AL detection scorer fails for object detection

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#335]
## Error
![image](https://user-images.githubusercontent.com/1522766/116398967-ad9f7980-a828-11eb-8583-135e29b8e7b4.png)
## Reproduction:
`np.partition([[1.]],-2, axis=1)` yields `ValueError: kth(=-1) out of bounds (1)`
## Possible cause of error:
https://github.com/lightly-ai/lightly/blob/b064ab7f077867ab1fe4ca1a3977090701856c26/lightly/active_learning/utils/object_detection_output.py#L1[…]27
tries to do a one-hot-encoding without knowing the number of classes. Thus if max(labels) is only 1, only one class is encoded and the probability vector only has a length of 1. Thus partitioning it into 2 fails.

### 1. Prevent the error cause
Create the class_probabilities vector correctly with a given number of classes.
### 2. Handle the error (MUST DO, We all agree on it)
In the ScorerClassification handle the case where there is only a single class
### 3. General solution
The class_probabilities do not make sense at all if the ObjectDetectionOutput is created from scores. Thus we could also not create the `class_probabilities` in this case and not compute any classification scores if the `class_probabilities` are unset.

Solution 1 and 3 are exclusive, solution 2 can be combined with the other solutions.

## How to work on this issue
- First write a unittest reproducing the error by using ClassificationScorer.calculate_scores()
- Next fix this unittest with solution 2.
- Do not work on Solution 3 yet (another issue)

**Comment by philippmwirth** [comment]
Let's do solution 2 for sure. There's no reason not to safeguard this.

As for the other two I think both solutions are fine. What are your favorites @MalteEbner and @IgorSusmelj ?

**Comment by IgorSusmelj** [comment]
I'm also in favor of resolving this in the `ScorerClassification`

**Comment by MalteEbner** [comment]
I am for solutions 2+3. It simply does not make sense to calculate scores which will always be 1 (for all there uncertainty scorers).

**Comment by philippmwirth** [comment]
Ok for me, @IgorSusmelj ?

**Comment by IgorSusmelj** [comment]
Let's, for now, make sure we can compute scores for all cases. Thus option 2. Other object detection frameworks give class_probabilities. I can have a look at whether I can update the tutorial without a lot of modifications to get them as well.

**Comment by MalteEbner** [comment]
> Problem is then that we have scores which work for some cases and not for others.
We have that problem anyway, as scores that are always 0 work in the sense of no errors but not in the sense of sampling better. And I prefer getting a clear error to doing a sampling and only finding out much later that it did not work that well because I did not provide class probabilities. Better fail with an error than silently.

**Comment by philippmwirth** [comment]
Let's do 2) now and 3) next sprint, as @IgorSusmelj suggested. This whole thing got really complicated with the introduction of the classification scores for object detection. Let's simplify quickly.
