### ISSUE TITLE
Active Learning Tutorials: align setting of variables

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#350]
We should follow one single approach how to set variables like the `token` or `dataset_id` in the active learning tutorials (and possibly also other tutorials):

## Approach A:
https://github.com/lightly-ai/lightly/blob/c437183b8726b20d4bb5a7c97e02d3fdf21b14c6/docs/source/tutorials_source/platform/tutorial_active_learning_detectron2.py#L130-L140
The user sets the variables once in the lightly-magic command and once in the python code. For generating the docs there is an additional function to read the variables in python from the environment instead.

## Approach B:
https://github.com/lightly-ai/lightly/blob/2adda61561bc2917c5ca62e749f447b6e92f3b2d/docs/source/tutorials_source/platform/tutorial_active_learning.py#L182-L184
The user sets all variables once via command line as environment variables. Then the environment variables are read both in the lightly-magic command and in the python code. Thus the user only has to set each variable once and does not need to change anything in the python code.

## Advantages of A vs. B:
The user does not need to use any environment variables and thus does not need to know about the CLI `export` commands, the `$OPERATOR` and the `os.getenv` function.
## Advantages of B vs. A:
The user only needs to set the variables once. There is no code only used for generating the code (the `try_get_token_and_id_from_env` function) and using this function does not need to be commented out.

## `new_dataset_name` vs. `dataset_id`
Orthogonal to this, we should decide whether to use the `new_dataset_name` or `dataset_id` in the `lightly-magic` command

**Comment by guarin** [comment]
Tutorials for active learning live now in our new docs: https://docs.lightly.ai/docs This issue is no longer needed.
