### ISSUE TITLE
error simCLR using vgg16 backbone

### ISSUE THREAD

**Issue by ramdhan1989** [lightly-ai/lightly#357]
Hi, this is really good application. I am playing around with this package recently. I got an error when trying to train simCLR using VGG16 backbone. 
```
collate_fn = data.ImageCollateFunction(input_size=80, cj_prob=0.5)
dataset = data.LightlyDataset(input_dir='path')

 dataloader = torch.utils.data.DataLoader(
    dataset,                # pass the dataset to the dataloader
    batch_size=128,         # a large batch size helps with the learning
    shuffle=True,           # shuffling is important!
    collate_fn=collate_fn)  # apply transformations to the input images
resnet = torchvision.models.vgg16(pretrained=True)
resnet = nn.Sequential(*list(resnet.children())[:-2])

model = models.SimCLR(resnet, num_ftrs=2048, out_dim=128)
criterion = loss.NTXentLoss(temperature=0.5)

optimizer = torch.optim.SGD(model.parameters(), lr=1e-0, weight_decay=1e-5)
embedding_model = embedding.SelfSupervisedEmbedding(
    model,
    criterion,
    optimizer,
    dataloader)

embedding_model.train_embedding( max_epochs=10)
```

I got an error below
`Runtimerror: mat1 and mat2 shapes cannot be multiplied (131072×2 and 2048×2048)`

any suggestion ?

thank you

**Comment by philippmwirth** [comment]
Hi @ramdhan1989, it looks like the output shape of your backbone is incompatible with the input shape of our prediction heads. Can you please try adding a `AdaptiveAvgPool2d` layer to your backbone as described [here](https://docs.lightly.ai/getting_started/advanced.html#models) and then set the `num_ftrs` of the `SimCLR` to `512`?

Let me know how it goes :)

**Comment by ramdhan1989** [comment]
@philippmwirth yes correct it seems AdaptiveAvgPool2d should have size 1. since VGG16 has AdaptiveAvgPool2d size 7 , it become incompatible and it works now after changing it to size 1. 

thank you

**Comment by philippmwirth** [comment]
Great, glad to help!
