### ISSUE TITLE
Add lightly-magic to the docs

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#358]
The documentation has currently no information about `lightly-magic`.

**Comment by pranavsinghps1** [comment]
I will get it done.

**Comment by IgorSusmelj** [comment]
A few commands I use and think are very useful are the following:

#### Create an embedding and upload the images + embeddings to web app
`lightly-magic  input_dir=input_dir trainer.max_epochs=0  token=yourToken datasetId=yourDatasetId`
- `trainer.max_epochs=0 ` --> Makes sure we don't train a model but just run inference
- `token=yourToken` --> Your authentication token
- `datasetId=yourDatasetId` --> The datasetId to upload our data to

#### Create an embedding and upload the images + embeddings to web app
`lightly-magic  input_dir=input_dir trainer.max_epochs=0 loader.num_workers=8 token=yourToken new_dataset_name=myNewDataset`
- `trainer.max_epochs=0 ` --> Makes sure we don't train a model but just run inference
- `loader.num_workers=8` --> Use 8 workers in the dataloader (use the number of CPU cores here for faster processing)

### Train an embedding model and upload images + embeddings to web app
`lightly-magic  input_dir=input_dir trainer.max_epochs=10 loader.batch_size=128 loader.num_workers=8 token=yourToken new_dataset_name=myNewDataset`
- `trainer.max_epochs=10` --> Train a model for 10 epochs
- `loader.batch_size=128` --> Use a batch size fo 128 for training and embedding
