### ISSUE TITLE
How to save model during training for every epoch

### ISSUE THREAD

**Issue by ramdhan1989** [lightly-ai/lightly#362]
Hi, is there any way how to save the model during the training for every epoch ? 

thanks

**Comment by philippmwirth** [comment]
Hi, there is but it's a little hacky at the moment. You can set the flag `checkpoint_callback.save_last=True` for the `SelfSupervisedEmbedding`. So it would look something like this:

```python
encoder = SelfSupervisedEmbedding(....)

# the following line will enable checkpoints after every epoch
encoder.checkpoint_callback.save_last = True
```

**Comment by philippmwirth** [comment]
Hi @ramdhan1989 sorry for the late response. You can use the `load_from_state_dict` function to load your checkpoint:

https://github.com/lightly-ai/lightly/blob/32b0c08dadd92a49401d9b10ec22522368a72735/lightly/cli/_helpers.py#L140

**Comment by ramdhan1989** [comment]
I tried to use def load_from_state_dict as mentioned above : 
```
model_ = models.alexnet()
model = nn.Sequential(*list(model_.children())[:-2],
                      nn.AdaptiveAvgPool2d(1))
ckpt = torch.load('alexnet_backbone_params.pth')
load_from_state_dict(model, ckpt)
```
then there is an error as shown below : 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-97-6a6381d6fb47> in <module>
      3                       nn.AdaptiveAvgPool2d(1))
      4 
----> 5 a = load_from_state_dict(model, ckpt)

<ipython-input-96-f41edb2ca826> in load_from_state_dict(model, state_dict, strict, apply_filter, num_splits)
    147 
    148     # step 3: load from checkpoint
--> 149     model.load_state_dict(state_dict, strict=strict)

~\AppData\Local\Continuum\anaconda3\envs\h20\lib\site-packages\torch\nn\modules\module.py in load_state_dict(self, state_dict, strict)
   1222         if len(error_msgs) > 0:
   1223             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1224                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1225         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1226 

RuntimeError: Error(s) in loading state_dict for Sequential:
	Missing key(s) in state_dict: "0.0.weight", "0.0.bias", "0.3.weight", "0.3.bias", "0.6.weight", "0.6.bias", "0.8.weight", "0.8.bias", "0.10.weight", "0.10.bias". 
	Unexpected key(s) in state_dict: "". 
```
Then, I tried this (but I don't know it load correctly or not but it doesn't give any error)
```
model_ = models.alexnet()
model = nn.Sequential(*list(model_.children())[:-2],
                      nn.AdaptiveAvgPool2d(1))

ckpt = torch.load('alexnet_backbone_params.pth')
model.load_state_dict(ckpt['alexnet_backbone_parameters'])
```
Please advice

thank you

**Comment by philippmwirth** [comment]
Yes, your approach should work fine.

**Comment by ramdhan1989** [comment]
> Hi, there is but it's a little hacky at the moment. You can set the flag `checkpoint_callback.save_last=True` for the `SelfSupervisedEmbedding`. So it would look something like this:
> 
> ```python
> encoder = SelfSupervisedEmbedding(....)
> 
> # the following line will enable checkpoints after every epoch
> encoder.checkpoint_callback.save_last = True
> ```

Hi @philippmwirth , using this approach, what is the name of saved file, file extension, and location of file ? I only can find lightning_logs/version_1/hparams.yaml
please advice

thanks

**Comment by philippmwirth** [comment]
It should be at `lightly_outputs/[TIMESTAMP]/last.ckpt`. Can you check if this file exists?

**Comment by ramdhan1989** [comment]
> It should be at `lightly_outputs/[TIMESTAMP]/last.ckpt`. Can you check if this file exists?

I can't find it inside the same folder with where my ipynb is located. Is it only applicable for CLI ? I run it from notebook.

**Comment by philippmwirth** [comment]
Ah yes, this is for the CLI. When working from a notebook it should appear in the working directory as `last.ckpt`.
Can you run `tree .` in your working directory and show me the output?

**Comment by ramdhan1989** [comment]
This is tree directory :

![image](https://user-images.githubusercontent.com/41245856/119751537-8db1b300-bec5-11eb-854b-91ffe96fa581.png)

there is only one folder generated automaticaly "lightning_logs"

thank you

**Comment by ramdhan1989** [comment]
I think it works when adding this 
embedding_model.checkpoint_callback.save_top_k = -1

thank you

**Comment by IgorSusmelj** [comment]
Hi @ramdhan1989, 

yes,  your trick should work as well. Great, that you figured out a way to solve the problem.

Let us know if there are other issues or questions!

**Comment by divypandya** [comment]
Hey, I was wondering if there is some way to specify "period" argument in checkpoint just like we have in pl.callbacksModelCheckpoint, as if I am training for longer epochs I wouldn't want to save the model after each epoch!
