### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'to'  when trying to get embedding

### ISSUE THREAD

**Issue by ramdhan1989** [lightly-ai/lightly#364]
I got error when trying to do .embed after training the model. The error is as follow :
```
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-23fdc1e43775> in <module>
----> 1 embeddings, _, fnames = embedding_model.embed(dataloader)

~\AppData\Local\Continuum\anaconda3\envs\h20\lib\site-packages\lightly\embedding\embedding.py in embed(self, dataloader, device, to_numpy)
    108             for (img, label, fname) in pbar:
    109 
--> 110                 img = img.to(device)
    111                 label = label.to(device)
    112 

AttributeError: 'tuple' object has no attribute 'to'
```
I follow exactly what has been written in the documentation. below is how I state the dataloader. the training process is successful. 
```
collate_fn = data.ImageCollateFunction(input_size=80, cj_prob=0.5)
dataset = data.LightlyDataset(input_dir='path_to_images')

dataloader = torch.utils.data.DataLoader(
    dataset,               
    batch_size=128,        
    shuffle=True,        
    collate_fn=collate_fn) 
```
my data structure is directly point to images inside the path (no sub folder)
```
path_to_images/
    >>> # `- img1.png
    >>> # `- img2.png
```

when I loop the dataloader 
```
for (img, label, fname) in dataloader:
    print(len(img), img[0].shape, img[1].shape)
```
the result is 
`2 torch.Size([128, 3, 80, 80]) torch.Size([128, 3, 80, 80])`

img is a tuple containing two tensor with same size, what are they refer to ?

please advice
thanks

**Comment by philippmwirth** [comment]
Hi @ramdhan1989, please note that the collate functions implemented in `lightly` are built for contrastive self-supervised learning methods and will therefore always return a tuple of image batches. So your loop should read:
```python
for ((img0, img1), label, fname) in dataloader:
    pass
```

Could you link me to where the documentation is wrong so that we can update it? Thanks in advance :)

**Comment by ramdhan1989** [comment]
Hi @philippmwirth , I am sorry, I forgot to use new dataloader. I must add something like this : 
```
# make a new dataloader without the transformations
dataloader = torch.utils.data.DataLoader(
    dataset,        # use the same dataset as before
    batch_size=1,   # we can use batch size 1 for inference
    shuffle=False,  # don't shuffle your data during inference
)
```
anyway, I have restart my notebook and save the backbone as mentioned in this link [https://github.com/lightly-ai/lightly/issues/287](url) . the example use ResNetGenerator to reload the checkpoint. Meanwhile, I am using alexnet for my backbone. do you have example to load model using non resnet backbone ? is the embedding result same if we get from 
embedding_model.embed(dataloader) compared to the one from this code
```
ckpt = torch.load('model.pth')
backbone_new.load_state_dict(ckpt['resnet18_parameters'])
backbone_new.eval()
output = backbone_new(some_input_tensor)
```
can we use something like dataloader to replace "some_input_tensor"
please advise
thanks

**Comment by philippmwirth** [comment]
I'm not sure I cokmpletely understand your question. The way you show above to load your backbone should work. You can then simply set the backbone of the model to the `backbone_new` and should be good to go.

Yes, you can simply use the `LightlyDataset` without changing the `collate_fn` like you would do it with any other pytorch dataset.
