### ISSUE TITLE
Lightly Dataset is slow at indexing larger datasets

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#384]
`LightlyDataset` is significantly slower than a simple `os.listdir` (500ms vs 50ms with a folder of 100k images). Let's figure out whether we can improve.

**Tasks:**

- [x] Figure out where we spend most of the time
- [x] Figure out whether we can improve

**Comment by IgorSusmelj** [comment]
I looked briefly into this. There are a few points where we could get 20-30% more speed. But they would require us to use a custom dataset instead of relying on the torchvision `ImageFolder`. 

I made an issue here: https://github.com/pytorch/vision/issues/3902

**Comment by philippmwirth** [comment]
This is related to [617](https://github.com/lightly-ai/lightly-core/issues/617).

Some of the reasons:
- `LightlyDataset` makes several calls to `os.listdir` (total of 3). This could be done more efficiently.
- `LightlyDataset` uses `os.path.join` which can be slow if done repeatedly but there is no way around this.

Proposal: Let's be more resourceful with the calls to `os.listdir` in [this function](https://github.com/lightly-ai/lightly/blob/ffabd63bd340c1cc69def46b3c772dcfc783efa4/lightly/data/_helpers.py#L71). This should carve off an easy 100ms on the dataset you described above.

Bonus: If there's a quick way to figure out whether a directory contains subdirectories which doesn't require `os.path.join` (as opposed to [our function](https://github.com/lightly-ai/lightly/blob/ffabd63bd340c1cc69def46b3c772dcfc783efa4/lightly/data/_helpers.py#L54)), we could further improve the performance.

**Comment by philippmwirth** [comment]
Apparently, `os.scandir` can also lead to signficant speed-ups. See:
- https://stackoverflow.com/questions/800197/how-to-get-all-of-the-immediate-subdirectories-in-python
- https://docs.python.org/3/library/os.html#os.scandir
