### ISSUE TITLE
enhance the upload speed

### ISSUE THREAD

**Issue by japrescott** [lightly-ai/lightly#392]
using `lightly-upload `and `lightly-magic` is not very fast and does not utilise all the cores. There seems to be a bottleneck somewhere.

Tasks
- [ ] figure out where most of the time goes when processing
    - [ ] split apart numbers of images/s to `images/s processing` and `images/s uploading`
- [ ]  ensure when `num_workers` is set, we really process with the amount of workers

**Comment by MalteEbner** [comment]
As already discusssed, most of the time went into getting the write URLs:
https://lightly-ai.slack.com/archives/C014FJT529M/p1617137355009000

**Comment by MalteEbner** [comment]
The problem is still getting the write url:
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/20324507/121370886-63d4a380-c93d-11eb-875c-49f8c7ba0626.png">
Mode=full on 50 images in the clothing dataset small.

**Comment by MalteEbner** [comment]
One possible speedup would be the following:
Reduce the number of API calls per samples from 3 (create sample, get thumbnail write url, get image write url) to only one call:
- adapt the `create sample_by_dataset_id()`function to get passed additionally the mode (metadata, thumbnail, full)
- depending on the mode, additionally create the one or two signed write urls and return them.

**Comment by japrescott** [comment]
one big reason for the `get_sample_image_write_url_by_id` fn to take so long is because there is a random delay built in to circumvent failed uploads to google storage. I will be removing that part so we can get "pure" numbers on dev

**Comment by japrescott** [comment]
> <img alt="image" width="1158" src="https://user-images.githubusercontent.com/20324507/121370886-63d4a380-c93d-11eb-875c-49f8c7ba0626.png">

is there some way for me to generate such a chart with ease? would help me to debug

**Comment by MalteEbner** [comment]
Tested against dev and with a much slower internet connection:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/20324507/121436531-082c0980-c981-11eb-8884-5b31d08f222a.png">
Now getting the `sample_image_write_url` is not the bottleneck anymore, but the upload. I will test tomorrow again, but with a faster internet connection.

**Comment by philippmwirth** [comment]
@japrescott I wonder if it's this DB query which forms the bottleneck in the API:

https://github.com/lightly-ai/lightly-core/blob/3fc689d7b1fae9016b1a7d6c370dc785bb750e5a/appv2/packages/app-api/src/routes/v1/datasets/samples/samples.services.ts#L130

If so, we could save time by sending this information along with the request to get a write url.

**Comment by japrescott** [comment]
@philippmwirth there are two db queries happening; one for auth the other for getting the sample information. All queries are by id and thus are indexed and very fast. These queries cant really be considered a bottleneck.

Regarding your idea; As we dont want random writes, we cant trust the API user to send us this information.

As far as the slowdown, I noticed that calling `Thumbnail` (https://github.com/lightly-ai/lightly/blob/885f7a22c63d3df415dacd4ce6d6e0d0153cf5ca/lightly/api/api_workflow_upload_dataset.py#L160) creates a noticable lag for other threads to e.g write to console. Maybe we get hung up by GIL there?
