### ISSUE TITLE
Add example of using Barlow Twins

### ISSUE THREAD

**Issue by ramdhan1989** [lightly-ai/lightly#398]
Hi, I think it would be better to add tutorial of using Barlow twins

thank you

**Comment by philippmwirth** [comment]
That's a great idea, we'll look into it. Do you have a usecase in mind?

**Comment by ramdhan1989** [comment]
@philippmwirth I think common dataset like cifar is ok

**Comment by shikharmn** [comment]
Hey! I've been working on a Barlow Twins implementation trained on CIFAR-10 for my research work, I think this something I can do. Should I take up this work?

**Comment by philippmwirth** [comment]
This will be closed by #508.
