### ISSUE TITLE
Error on Comma AI Colab

### ISSUE THREAD

**Issue by dsantiago** [lightly-ai/lightly#401]
Hi guys, i got an unknown error when testing the commaai example in Colab

![image](https://user-images.githubusercontent.com/3484029/121163077-df8efd00-c824-11eb-94ad-6ae4a41133a0.png)

Just for reference of the lib version:

![image](https://user-images.githubusercontent.com/3484029/121163215-fc2b3500-c824-11eb-8980-bf4154a140ff.png)

**Comment by IgorSusmelj** [comment]
Could you retry? It looks like our infra is sweating because of the many new users.

**Comment by dsantiago** [comment]
Guys it worked now, tested here... Thanks for the effort... 

Closing the issue!

**Comment by dsantiago** [comment]
Sorry, i was a little bit fast the output was already from the notebook, i continue with the job id error... reopening...

**Comment by philippmwirth** [comment]
Hi @dsantiago, we are looking into it and will get back to you as soon as possible.

**Comment by philippmwirth** [comment]
We found the problem and are working on a fix. Thanks for letting us know! :)

**Comment by philippmwirth** [comment]
We implemented the fix on our side and for our ML engineer @MalteEbner the tutorial works now. Can you please try again?

**Comment by dsantiago** [comment]
Tested, took a while to run the code but it's fine now guys, thanks for the support!
