### ISSUE TITLE
Read dataset object-wise

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#412]
## Description
For object detection tasks, it should be possible to read a dataset object-wise, do the embedding on the objects cropped from the full image and then upload the object to the webapp.

## Proposed workflow:
- add cfg parameter `path_to_bounding_boxes`
- take the images and bounding box information (in yolo-format) and extract the cropped images into a temporary directory
- use this temporary directory as input directory for all following steps: Training, Embedding and Uploading are done object-wise automatically

## Open questions
- What is the exact format of the bounding box information? Yolo, but is it a csv of image_name/X1/Y1/X2/Y2 or yaml? What do we support?
- How are the two workflow steps implemented? 
    - Option A: The extraction and usage happens under the hood when the cfg param is passed. 
    - Option B: There is a separate lightly-crop command needing an output directory, used as input_dir for the following steps.  
      This also allows for options like having a cropping padding.

**Comment by IgorSusmelj** [comment]
Something like this?

We expect the dataset to be in the Yolo format:
```
`- data_root
  `- images
    `- img_001.jpg
    `- img_002.jpg
  `- labels
    `- img_001.txt
    `- img_002.txt
```
 
Then a user can run `lightly-crop`:

`lightly-crop images_dir=data_root/images labels_dir=data_root/labels output_dir=data_root/images_cropped padding=0.1`

That would translate into
- get images and labels from the folders
- store cropped images
- add a pudding of 0.1 = 10% to the crops

**Comment by MalteEbner** [comment]
Ideally use the dataset for MilkyWay for it: https://github.com/eg4000/SKU110K_CVPR19
