### ISSUE TITLE
Commits/PRs: ensure that all files are small

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#438]
## Description
- we want to prevent that large files get it the git history and bloat
- this could be prevented by pre-commit hooks, but they need to be installed
- alternatively / additionally we could have a GitHub action

## Example:
- ensure that the screenshots used for the documentation are rather small (<200kB) and not in the full resolution (>1MB)

**Comment by japrescott** [comment]
what kind of files are you talking about? cant we just add the file extension or folder to gitignore?

**Comment by MalteEbner** [comment]
I just followed the install instructions in the PRECOMMITHOOKS.md and now larger image > 500kB are prevented.
