### ISSUE TITLE
Add example to documentation to use Lightly together with Neuro

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#439]
Let's write a simple example on how to train a lightly embedding model using [Neuro](https://www.getneuro.ai/)

Requirements of the example code:

- Small dataset (max a few hundred images)
- Everything runs in a single Python script
- This example/ tutorial only covers the pip package and not the platform

The example should cover the following:

1. Create a dataset from a folder of images
2. Train an embedding model on the dataset
3. Embed the data using the trained model

The engineers from Neuro will help us refactoring the code to use their framework for training and inference. We just write normal Lightly code and they will help us updating the PR.

@MalteEbner proposes to put this issue on hold until
- Neuro supports Pytorch Lightning easily
- The refactoring of the lightly models is done, see #379

**Comment by MalteEbner** [comment]
I had a look at it and created a colab from our SimCLR tutorial: https://colab.research.google.com/drive/1v8gpH9qLFy5wNTvdq-7Yc5KQLRxe6KTg#scrollTo=tgY5ZPm5XElC

The main problem is that there is no good tutorial/documentation on how to use neuro with pytorch lightning. Thus I would propose to wait with this issue until Neuro has some documentation on how to do that.

Currently lightly uses pytorch lightning for training here:
https://github.com/lightly-ai/lightly/blob/c268464a494e5fe7a89b6087e180351e32856add/lightly/embedding/_base.py#L88-L90
