### ISSUE TITLE
Could you provide the Sentinel-2 satellite dataset mentioned in document?

### ISSUE THREAD

**Issue by likyoo** [lightly-ai/lightly#440]

**Comment by IgorSusmelj** [comment]
Hey @likyoo,
The dataset is 4.2GBytes and not so easy to share. Could you try it with one of the various datasets on Kaggle? https://www.kaggle.com/general/196396

You just need images in a folder for the tutorial to work.

**Comment by likyoo** [comment]
thanks a lot.
