### ISSUE TITLE
Where is pretrain weights?

### ISSUE THREAD

**Issue by CoinCheung** [lightly-ai/lightly#446]
Where could I download pretrain weights of these models?

**Comment by IgorSusmelj** [comment]
Hi @CoinCheung, we have only pre-trained backbones for some of the custom resnet configurations shown here: https://github.com/lightly-ai/lightly/blob/master/lightly/models/zoo.py

However, you might want to checkout our tutorials on how to use the pre-trained torchvision models: https://docs.lightly.ai/tutorials/package/tutorial_simclr_clothing.html

**Comment by CoinCheung** [comment]
Thanks for telling this.
