### ISSUE TITLE
AttributeError: module 'lightly.models' has no attribute 'modules'

### ISSUE THREAD

**Issue by etetteh** [lightly-ai/lightly#450]
I run into the following error when trying to use NNCLR's NN memory bank.
```
Traceback (most recent call last):  
File "train_nnclr.py", line 295, in <module>     
    model = NNCLRModel(backbone = backbone)
File "train_nnclr.py", line 164, in __init__    
    nn_replacer = lightly.models.modules.nn_memory_bank.NNmemoryBankModule(size=2** 16)
AttributeError: module 'lightly.models' has no attribute 'modules'
```

**Comment by philippmwirth** [comment]
Hi @etetteh thanks for reporting this! Could you let us know your Python and lightly versions please?

**Comment by etetteh** [comment]
I'm using Python 3.6.7 and lightly version 1.1.16

**Comment by philippmwirth** [comment]
Thanks, we will fix it ASAP. In the meantime you can use this workaround:
```python
>>> from lightly.models import modules
>>> modules.nn_memory_bank.NNMemoryBankModule(size=2**16)
```

**Comment by etetteh** [comment]
Thanks. Also, are you going to release MoCo V2, or I can add the necessary features to the existing one?
Thanks

**Comment by philippmwirth** [comment]
No one from our side is currently working on releasing MoCov2 although it would be an important addition to the repo.
It would be great if you would add the required features if you're interested in contributing :)

**Comment by philippmwirth** [comment]
The error most likely stems from a typo in the code: @etetteh used `NNmemoryBankModule` instead of the correct `NNMemoryBankModule`.

The following lines work:
```python
import lightly
lightly.models.modules.nn_memory_bank.NNMemoryBankModule(size=2** 16)
```
