### ISSUE TITLE
Add examples for all ApiWorkflow functions

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#458]
# Add examples for all ApiWorkflow functions

The `ApiWorkflow` class provides a lot of usability. You can e.g. create datasets, upload samples, upload embeddings, upload custom metadata, delete datasets, and more. But, currently, the documentation is rather thin. We should add a simple example on how to use these functions for all of them.

**Comment by Nike682631** [comment]
Is this issue available to work on?

**Comment by philippmwirth** [comment]
Yes, it is. It's also a good first issue as it's mostly documentation.

**Comment by Nike682631** [comment]
Please assign it to me. I'll start working on it.

**Comment by philippmwirth** [comment]
With pleasure :) Let us know if you need any help! 

Here's our [contribution guide](https://github.com/lightly-ai/lightly/blob/master/CONTRIBUTING.md).

**Comment by Nike682631** [comment]
Hi @philippmwirth , Is this issue still available to work on? Apologies for getting back after a long time.

**Comment by philippmwirth** [comment]
Completed.
