### ISSUE TITLE
Multi-worker upload of LightlySubset of videos

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#460]
# Multi-worker upload of LightlySubset of videos

Race conditions occur upon uploading a `LightlySubset` of a `VideoDataset` with multiple workers.

- [ ] Investigate where the race condition happens
- [ ] Figure out a solution to prevent this error
- [ ] Investigate what other scenarios might be affected by this problem

**Comment by guarin** [comment]
Dataset upload is deprecated.
