### ISSUE TITLE
Clean up navigation

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#463]
# Clean up navigation

The navbar in the docs has become quite cluttered. Especially the "First Steps" section has a lot of content which does not really belong there. We should regroup and clean it up.

To Do:
- [ ] Regroup / rewrite the introduction sites (see below for a suggestion)

Current state:

![grafik](https://user-images.githubusercontent.com/65946090/129161159-7bfdfb1a-b70b-443e-9ddf-47a32ac33328.png)

Suggested new structure:

- GETTING STARTED
    - Main Concepts (new page with the content from the current landing page)
    - Installation
    - Command-line Tool
    - Self-supervised Learning (new page with the content from "Lightly at a Glance"
    - Active Learning (move the concepts part to "Main concepts")
    - The Lightly Platform (optional - maybe merge it with AL)
- ADVANCED
    - Advanced Concepts (new page with contents of current "Advanced" page)
    - Benchmarks

**IMPORTANT**
> Just a quick reminder for anyone working on reshuffling our lightly docs page. Make sure your changes don’t affect the URLs as we would have broken links otherwise. I think the urls are from the folder structure but I’m not sure.
~ @IgorSusmelj

**Comment by japrescott** [comment]
One suggestion is to rename "Python API" to "PIP REFERENCE" or similar as to not confuse it with the REST API

**Comment by japrescott** [comment]
okey, I was more inspired by torch lightning that calls it `API REFERENCE` https://pytorch-lightning.readthedocs.io/en/latest/. Generally I like the word `reference`.

**Comment by philippmwirth** [comment]
Yes you're right, but they also have `Lightning Reference`... 🤔

Thinking about it, I would also be ok with something like `Lightly Reference` or `Package Reference` tbh.

**Comment by MalteEbner** [comment]
>Main Concepts (new page with the content from the current landing page)
After moving this, the landing page is quite empty. Furthermore, we are missing on overview of the lightly ecosystem:
We should tell that we have the following parts and how they fit together:
- SSL package
- Lightly Platform + Webapp
- CLI
- AL
- Docker
