### ISSUE TITLE
Redesign landing page

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#466]
# Redesign landing page of the docs

The goal of the landing page should be to guide the user directly to the parts of the documentation which are the most valuable to them.

To Do:
- [ ] Figure out a good concept for the design of the landing page
- [ ] Implement it

**Comment by Nike682631** [comment]
Is the landing page for the web app? I'd like to give it a shot :D

**Comment by philippmwirth** [comment]
Hi @Nike682631 

This issue is about the documentation. I will clarify this in the issue description.
