### ISSUE TITLE
Lightly Documentation: Figure out how to create landing page and overviews targeting different user groups

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#479]
Currently we have many different user groups for the lightly platform. Of course, some users may be part of multiple of these groups. 
A. potential customers, who want to evaluate our product offering
B. people with ML background who want to perform self-supervised learning
C. people who want some embeddings for further tasks (nearest-neighbour search, clustering, ...)
D. people who want to check out some cool ML stuff

We have many different subparts as part of the Lightly Ecosystem:
1. The SSL part, making up the core of the lightly package
2. The Lightly Platform + Web App
3. The Active Learning framework
4. The CLI for doing SSL and/or for using the Lightly Platform
5. The docker

Our user groups probably have their interest in the following parts:
A. potential customers: in all subparts, not necessarily in detail. E.g. they probably don't care that much about the building blocks of the SSL part (collate function, ...).
B. people for SSL: mostly 1 in detail, perhaps also 4 for the CLI
C. people for embeddings: mostly the CLI for SSL, partly 1.
D. people for cool ML stuff: 1-4, depending on their interest, tutorials are great.

How can we have a landing page and overview pages (e.g. main concepts) that 
a) attract all user groups
b) link these user groups to the subpages of their interest

**Comment by sujanneeraj** [comment]
Hi,

Is this issue still offen. If yes, I would like to contribute to it. Could you guide me a bit? 

Thank You

**Comment by MalteEbner** [comment]
Hey @sujanneeraj,

yes, this issue is still open. Thank you for wanting to work on it, we always welcome that! As it is a "Figure Out" issue, its result should be a concept of how to guide the users. This concept could be in form of a sketch on paper, or different drafts and comparisons between them. Then it should also include a description of what should be implemented, i.e. follow-up issues.

As a first step, you could think of yourself: Which user group (A-D) do you fit in best? And which subpages of lightly were of biggest interest to you? Which ones have you looked at first? And at which ones would you have liked to looked at first? What would have been the ideal guidance for you for the lightly documentation?
