### ISSUE TITLE
Lightly-Crop: memory leak

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#485]
When using lightly-crop some users experience a memory leak.

- [ ] Try to reproduce it.
- [ ] Fix it

**Comment by IgorSusmelj** [comment]
Looked into the issue. There might be a leak when we have many objects cropping out of an image. However, the impact is rather low. I'll check on various datasets and environments.

**Comment by IgorSusmelj** [comment]
The only problematic area I found is the method here: https://github.com/lightly-ai/lightly/blob/ce915f7303a07ceaf9ba4905a67689865a18c9bf/lightly/utils/cropping/crop_image_by_bounding_boxes.py#L13

We load all crops into the memory. It would be better to inline this method and process each crop sequentially.

**Comment by MalteEbner** [comment]
> The only problematic area I found is the method here:
> 
> https://github.com/lightly-ai/lightly/blob/ce915f7303a07ceaf9ba4905a67689865a18c9bf/lightly/utils/cropping/crop_image_by_bounding_boxes.py#L13
> 
> We load all crops into the memory. It would be better to inline this method and process each crop sequentially.

I agree, We should e.g. add the filepaths and class indices as argument, then we can save the cropped image directly and don't need to have a list of cropped images which is returned.
