### ISSUE TITLE
Refactoring: write new momentum encoder (make it more flexible)

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#494]
The momentum encoder should be

- not a Mixin anymore
- be flexible in terms of backbone, projection/prediction heads
- This includes supporting multiple projection/prediction heat combine, e.g. for SimSiam

A very good baseline for this is provided in https://github.com/lightly-ai/lightly/blob/483-SSL-model-refactoring-remove-models%2C-provide-full-examples-instead-me/lightly/models/modules/momentum_encoder.py

Furthermore, add a deprecation warning to the olde momentum encoder.

**Comment by IgorSusmelj** [comment]
I would aim for something along the lines of:

```python
# init
backbone = resnet18()
moco = MoCo(backbone)
moco_momentum = copy.deepcopy(moco)

# forward pass

# update momentum
update_momentum(moco, moco_momentum, m=0.999)

x0, x1 = data
out0 = moco(x0)

# shuffle batch
x1_shuffled, shuffle = batch_shuffle(x1)
out1 = moco_momentum(x1)
out1 = batch_unshuffle(out1, shuffle)
```

**Comment by MalteEbner** [comment]
I agree that the momentum update and the batch shuffling are two different things, they should be done separately. If we do that, I would not have any a high-level wrapper at all. Instead, I would only implement the three basic functions needed:
```
update_momentum(parent_model, model_to_update, momentum)
batch_shuffle(x)
batch_unshuffle(x, shuffle_order
```

@IgorSusmelj What confuses me in your pseudocode is that you assume there is a MoCo(backbone). Don't we want to deprecate that? Instead we would need something like

**Comment by IgorSusmelj** [comment]
Yes, it will be deprecated. I just added it to give a better idea.
