### ISSUE TITLE
Add default parameters for all projection heads

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#507]
# Add default parameters for all projection heads

It's helpful to know what the default parameters were in the papers to get started. We should add the default projection head parameters which were used for pre-training on Imagenet to all projection and prediction heads in `lightly/models/modules/heads.py`.

**Comment by himanshu007-creator** [comment]
Hi, I would like to work on this issue. Pleas guide me further ^_^

**Comment by philippmwirth** [comment]
Hi @himanshu007-creator that's great! 

In case this is your first time contributing to an open source package, I would recommend you to take a look at our [contribution guide](https://github.com/lightly-ai/lightly/blob/master/CONTRIBUTING.md). Let me know if you have any questions, I'm happy to help :)

Here is the list of implemented papers to get you started:
- [Bootstrap your own latent: A new approach to self-supervised Learning, 2020](https://arxiv.org/abs/2006.07733)
- [Barlow Twins: Self-Supervised Learning via Redundancy Reduction, 2021](https://arxiv.org/abs/2103.03230)
- [SimSiam: Exploring Simple Siamese Representation Learning, 2020](https://arxiv.org/abs/2011.10566)
- [MoCo: Momentum Contrast for Unsupervised Visual Representation Learning, 2019](https://arxiv.org/abs/1911.05722)
- [SimCLR: A Simple Framework for Contrastive Learning of Visual Representations, 2020](https://arxiv.org/abs/2002.05709)
- [NNCLR: Nearest-Neighbor Contrastive Learning of Visual Representations, 2021](https://arxiv.org/pdf/2104.14548.pdf)
- [SwaV: Unsupervised Learning of Visual Features by Contrasting Cluster Assignments, 2021](https://arxiv.org/abs/2006.09882)

**Comment by guarin** [comment]
This has been implemented in #798
