### ISSUE TITLE
LightlyDataset with filenames bug on subfolders

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#535]
# LightlyDataset with filenames bug on subfolders

For 

```python
dataset = LightlyDataset(
    input_dir=tmp_dir,
    filenames=filenames
)
```

I get an error when `filenames` doesn't contain at least one image from every subfolder, e.g.

```
data/
L subfolder_1/
    L  img0.png
    L  img1.png
L subfolder_2/
    L img0.png
```

Then `filenames=[subfolder_1/img0.png']` will fail.

**Comment by MalteEbner** [comment]
The problem is even worse if you use `./` as input_dir, because then it creates the directory `lightly_outputs` causing this error.

**Comment by MalteEbner** [comment]
I have discussed this issue in length with some developers from torchvision: https://github.com/pytorch/vision/issues/4925

The key takeaway is: Do not use `LightlyDataset(input_dir)` on input_dirs which contain subdirectories without images you want to upload. This ensures that the labels returned when iterating over the `LightlyDataset(input_dir)` are continuous, start with 0 and that there is at least one image for every label.
