### ISSUE TITLE
Implement SimSiam Representation Learning

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#54]
As proposed by users u/lfotofilter and u/AiDreamer on Reddit.

Add an implementation of the SimSiam Representation Learning framework.
- [Paper](https://arxiv.org/pdf/2011.10566.pdf)

**Comment by busycalibrating** [comment]
I'd also potentially be interested in helping out with this implementation!

**Comment by philippmwirth** [comment]
Sounds great! Maybe we can get some inspiration from [here](https://github.com/PatrickHua/SimSiam)?

As with BYOL, I would probably start with the implementation of the loss function first and then add the architecture.

**Comment by philippmwirth** [comment]
#57 relevant

**Comment by busycalibrating** [comment]
Sounds good, and I'll take a look through the way things are implemented in this library. I haven't made too many open-sourced contributions yet so forgive me if there's a bit of a learning curve!

**Comment by busycalibrating** [comment]
I'm wondering where would be the best place to ask some more detailed questions that may not make the most sense to discuss here? I see that you guys have a discord - would that be better (or if you have a Gitter or something)?

**Comment by philippmwirth** [comment]
Sure, the discord is a great place to ask questions.

**Comment by philippmwirth** [comment]
Hi @busycalibrating, are you still working on this? I have some time this week and I could help you with the PR if you're interested :)

**Comment by busycalibrating** [comment]
Just bogged down in exam week, but I should have some time tomorrow to wrap up the loose ends!

**Comment by philippmwirth** [comment]
Cool, let me know if I can help. I hope your exams went well!
