### ISSUE TITLE
Implement BYOL

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#55]
As proposed by user u/extracoffeeplease on Reddit.

Add an implementation of the BYOL framework.
- [Paper](https://arxiv.org/pdf/2006.07733.pdf)

**Comment by laurenmoos** [comment]
I'd love to take this (or perhaps the next actionable step of this at least) 

btw really cool project!

**Comment by busycalibrating** [comment]
If there's the need, I'd be potentially interested in helping out too!

**Comment by philippmwirth** [comment]
Hi both!

In my opinion, it would be best to start with an implementation of the [BYOL loss](https://arxiv.org/pdf/2006.07733.pdf) in the module `lightly.loss`.
A second step would then be to add the architecture under `lightly.models`.

The following links might be helpful:
- [Lightly: How to contribute](https://github.com/lightly-ai/lightly/blob/develop/CONTRIBUTING.md)
- [Inspiration: NTXEntLoss](https://github.com/lightly-ai/lightly/blob/develop/lightly/loss/ntx_ent_loss.py) (no need to inherit from MemoryBank for BYOL)

Let me know if anything is unclear or if you have suggestions. We're looking forward to your contribution!

**Comment by philippmwirth** [comment]
#57 relevant

**Comment by busycalibrating** [comment]
Sounds good! I'll let @laurenmoos take a lead on this - let me know if you want to collaborate on anything or if you'd rather take it on yourself.

**Comment by laurenmoos** [comment]
PR: 

https://github.com/lightly-ai/lightly/pull/64

**Comment by laurenmoos** [comment]
I will respond to @philippmwirth 's comments but leave things staged until I can rebase in the model architecture changes

I will make a few additional tickets and inline them with the next pull request iteration (experiment params structure (to discuss), augmentation functions (likewise to discuss)

**Comment by philippmwirth** [comment]
There's a working version of BYOL [here](https://github.com/philippmwirth/byol) (already implemented in the way `lightly` would use it). It would only take some minor brush ups and finishing touches to create a PR. If anybody feels like it, please let me know and I'll assign the issue to you :)

**Comment by pranavsinghps1** [comment]
I want to work on this!

**Comment by philippmwirth** [comment]
Hi @pranavsinghps1, how's it coming? Can we assist you in any way?
