### ISSUE TITLE
Rewrite Docs with Low-Level Building Blocks: Self-supervised Learning

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#555]
# Rewrite Docs with Low-Level Building Blocks: Self-supervised Learning

The [self-supervised learning] page still contains mid- and high-level building blocks.

- [x] Change the training code to a plain pytorch trainig loop
- [x] Change the embedding code to manually loop through the images

Related to #493.

**Comment by guarin** [comment]
We should probably also update the colab notebook: https://colab.research.google.com/drive/1ubepXnpANiWOSmq80e-mqAxjLx53m-zu?usp=sharing

**Comment by guarin** [comment]
Colab is updated.
