### ISSUE TITLE
Rewrite Docs with Low-Level Building Blocks: Advanced Concepts in SSL

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#557]
# Rewrite Docs with Low-Level Building Blocks: Advanced Concepts in SSL

The [acvanced concepts in SSL](https://docs.lightly.ai/getting_started/advanced.html) page still contains mid- and high-level building blocks.

- [ ] Correct this sentence: "Lightly supports at the moment the following two models for self-supervised learning"
- [ ] Remove the mid-level building block in [models](https://docs.lightly.ai/getting_started/advanced.html#models)

Related to #493.

**Comment by guarin** [comment]
We should also add NegativeCosineSimilarity to the [list of loss functions](https://docs.lightly.ai/getting_started/advanced.html#losses) and remove the symmetric version from.

For the models we could replace the links to the documentation with links to the tutorials.
