### ISSUE TITLE
MoCo symmetric loss should not update memory bank

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#564]
The current implementation of MoCo in the benchmark uses a symmetric loss: https://github.com/lightly-ai/lightly/blob/592d8f899a427dd0763b66ef856c8ffd74179357/docs/source/getting_started/benchmarks/cifar10_benchmark.py#L212-L213

But this is problematic as `x1` will be added to the memory bank after the `loss_1` calculation. In the calculation for `loss_2` it will then be retrieved from the bank as a negative example.

**Comment by philippmwirth** [comment]
Solved by #565 and #579
