### ISSUE TITLE
Refactor models

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#57]
The SimCLR and MoCo architectures are currently implemented as standalone architectures.
Before adding new architectures like BYOL or SimSiam we should probably make use of the existing code, e.g.
- Divide architectures into more general frameworks (in our case: with momentum updates vs. without momentum updates).
- Have SimCLR, MoCo, BYOL, SimSiam, etc inherit from the respective generalized architectures.

**Comment by busycalibrating** [comment]
+1

Do you have an idea for base classes/interfaces that you'd like to enforce, and an idea of how long it will be before things are refactored into this format?

**Comment by philippmwirth** [comment]
At the moment, I'm thinking of something like this (names are provisionally):

```
ResNetEncoder
+-- SingleResNetEncoder
    +-- ResNetSimCLR
    +-- ResNetSimSiam
+-- DualResNetEncoder
    +-- ResNetMoCo
    +-- ResNetBYOL
```

Unfortunately, I can't give you an exact timeline but since we have rather quick development cycles I would say in the next weeks.

**Comment by busycalibrating** [comment]
Do you tie each self-supervised model to a specific backbone? I'm fairly new to this subject so I don't know the details of all the different types of approaches, but it was my understanding that they were _fairly_ model agnostic?

For example this, [BYOL implementation](https://github.com/lucidrains/byol-pytorch) allowed you to hook up your own model into the BYOL architecture.

**Comment by philippmwirth** [comment]
Good point, currently the layer of abstraction is implemented in `lightly.embedding`, so if someone wants to use a custom model that person would have to write its own implementation of the self-supervised model. This refactoring would be a great time to change this and accept different backbones. I have changed the example names in the comment above.
