### ISSUE TITLE
Allow download of full dataset using CLI

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#6]
At the moment, our CLI only supports two ways of downloading datasets:

1. We only download the filenames and manually take care of copying the right samples
2. We download the filenames and automatically copy samples from a source folder to a destination folder.

However, it would be nice to download the full dataset (original images) if they are available from the platform to a destination folder.

**Comment by philippmwirth** [comment]
How would you prefer to handle it? I see the following options:
- The new download replaces the old one
- The new download runs under `lightly-download` and the old one under `lightly-copy`
- The new download runs under `lightly-download` when a certain argument is passed

**Comment by IgorSusmelj** [comment]
I would go with `lightly-download`. We already have too many CLI options. I would try to simplify wherever possible, no?

How about this:
If the user passes `input_dir` we do a copy. If not we download?

**Comment by MalteEbner** [comment]
I agree with Igor's proposal:
```bash
# the new download
lightly-download token=TOKEN dataset_id=DATASETID out_dir="path/to/out/dir"
#the old download copying images from one folder to another
lightly-download token=TOKEN dataset_id=DATASETID out_dir="path/to/out/dir" input_dir="path/to/in/dir" 
```
