### ISSUE TITLE
Update backbones to use default PyTorch implementations

### ISSUE THREAD

**Issue by busycalibrating** [lightly-ai/lightly#62]
Currently, the primary ResNet backbone uses a custom implementation that would not be directly compatible with the default PyTorch implementations (in addition to having a slightly different layer configuration). I think it would be advantageous to move to using the standard models offered in torchvision as most people likely default to those.

**Comment by MalteEbner** [comment]
I agree that using the standard models offered in torchvision would be better than having our own models.
What we are currently thinking about is a good migration strategy, as the current checkpoints are only compatible with the current resnet models, but not necessarily with the default pytorch ones.

**Comment by IgorSusmelj** [comment]
Would keep the old ResNet structure for datasets such as cifar10. Images of size 32x32 don't work well with the standard ResNets. The 7x7 conv with stride=2 and maxpool reduce the feature a lot.

**Comment by guarin** [comment]
We switched to the default torchvision resnets in all our [model examples](https://docs.lightly.ai/self-supervised-learning/examples/models.html).
