### ISSUE TITLE
Can't access to ApiWorkflowClient.get_filenames_in_tag()

### ISSUE THREAD

**Issue by naayem** [lightly-ai/lightly#635]
Hello,
After setting up my **api client** and using the command:
`api_client.get_filenames_in_tag(tag_data='active-learning-loop-1')`

I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ApiWorkflowClient' object has no attribute 'get_filenames_in_tag'

**Comment by IgorSusmelj** [comment]
Hi @naayem, thanks for reporting the issue. Could you share more information about the version you are using and some more context. Were you following one of the tutorials?
We're currently having issues with the latest API version (lightly 1.2.0). Maybe installing lightly 1.1.23 could fix the issue?
`pip uninstall lightly` followed by `pip install lightly==1.1.23`

**Comment by philippmwirth** [comment]
The following lines work for me in `lightly==1.2.1` 

```python
>>> client = lightly.api.ApiWorkflowClient(dataset_id, token)
>>> client.get_filenames_in_tag
<bound method _TagsMixin.get_filenames_in_tag of <lightly.api.api_workflow_client.ApiWorkflowClient object at 0x7ffb99a4f350>>
>>> lightly.__version__
'1.2.1'
```

**Comment by MalteEbner** [comment]
The method `get_filenames_in_tag()` was added in https://github.com/lightly-ai/lightly/blame/master/lightly/api/api_workflow_tags.py
and became part of `lightly==1.2.0`
