### ISSUE TITLE
Did cifar10 dataset need gaussian blur

### ISSUE THREAD

**Issue by littleolex** [lightly-ai/lightly#648]
In the https://github.com/lightly-ai/lightly/blob/master/lightly/data/collate.py,  class SimCLRCollateFunction() presents a n example for using it,
collate_fn = SimCLRCollateFunction(
        >>>     input_size=32,
        >>>     gaussian_blur=0.,
        >>> )
but in https://docs.lightly.ai/examples/simclr.html
collate_fn = SimCLRCollateFunction(input_size=32)
so I wonder which one is the one you suggested?

**Comment by philippmwirth** [comment]
Hi @littleolex, in the paper the authors leave out Gaussian blur so I would recommend to use the first option:
```python
collate_fn = SimCLRCollateFunction(
    input_size=32,
    gaussian_blur=0.,
)
```

We will fix the example to do the same 👍

**Comment by littleolex** [comment]
Thank you for replying so quickly
