### ISSUE TITLE
Why are there different backbones across SSL methods in CIFAR10 benchmark?

### ISSUE THREAD

**Issue by JeanKaddour** [lightly-ai/lightly#650]
Hi, thank you so much for developing this great library, I found it extremely useful for my work!

I noticed that in the [CIFAR10 benchmark script](https://github.com/lightly-ai/lightly/blob/master/docs/source/getting_started/benchmarks/cifar10_benchmark.py), there are different backbones across the SSL methods. 

The two differences I've noticed are:
1. some use `torchvision.models.resnet18()`, others use `lightly.models.ResNetGenerator('resnet-18')`
    * I understand that for the CIFAR datasets, we want to use a variant that's slightly different than the ones in torchvision (which is typically used for ImageNet)
    * what I don't understand is why you did not use one variant consistently across all SSL methods 
2. some have an additional `nn.AdaptiveAvgPool2d(1)` layer at the end, some don't. 
    * my guess would be that this has something to do with the respective projection heads
    * to be safe, I hope you don't mind me asking

I'd highly appreciate any help!

**Comment by philippmwirth** [comment]
Dear @JeanKaddour thanks for bringing this up! It's most likely an oversight and we'll have to fix it and make it consistent.
The `nn.AdaptiveAvgPool2d(1)` ensures that the output of the backbone is compatible with the projection heads.

**Comment by JeanKaddour** [comment]
thank you very much!
