### ISSUE TITLE
How to generate labels from SimCLR Algorithm to convert Self-Supervised to Supervised Problem?

### ISSUE THREAD

**Issue by ya-stack** [lightly-ai/lightly#671]
I have trained SimCLR Model and got the nearest embeddings of a Query Image. 
Now, I want to create classes for these Nearest Embedded Images and want to save these images into the respective class folders.
It would be really helpful if you can provide a solution/approach to this.

Waiting for your response.
Thanks in advance.

**Comment by MalteEbner** [comment]
Hi @ya-stack !
Could you elaborate on what you desired output what look like?
I assume that you have a single query image and found its nearest neighbours in the embedding space. What do you want to do with these nearest neighbours? Do you want to save the corresponding images all in the same new folder?

And what do you mean by "creating classes"? If you want to label your images, you need a labelling tool. You could follow our tutorial on how to export the labels from the Lightly Platform to LabelStudio and label them there: https://docs.lightly.ai/tutorials/platform/tutorial_label_studio_export.html#

If you don't have you data on the Lightly Platform yet, upload them using the CLI: https://docs.lightly.ai/getting_started/dataset_creation/dataset_creation_local_upload.html

In the Lightly Platform you can browse through your images, view their nearest neighbours and manually select them, so you could also get the nearest neighbours of a query image there and do that step there.

**Comment by ya-stack** [comment]
Hi Team,
Thanks for your reply.

And for further clarification, I want to create a separate folder for each query image and its corresponding nearest neighbors so that I can use these images for other tasks. So, how can I do the same?

Thank you!

**Comment by ya-stack** [comment]
Hi Team,
Thanks for your reply.

And for further clarification, I want to create a separate folder for each
query image and its corresponding nearest neighbours so that I can use
these images for other tasks. So, how can I do the same?

Thank you!

**Comment by MalteEbner** [comment]
Hey @ya-stack 
In the Lightly Platform, you can create a separate tag for each query image and its nearest neighbours. Then you can download the tag with its filenames and images by going to "download".
