### ISSUE TITLE
Imagen segmentation

### ISSUE THREAD

**Issue by Jcastanyo** [lightly-ai/lightly#678]
Hi everyone,

I wonder if It is possible to apply these methods in image segmentation. In that case, is there any tutorial available? 

Thanks in advance.
Julio.

**Comment by guarin** [comment]
Hi,

Self-supervised learning can definitely used for pretraining an image segmentation network. In this case it is important to consider how many objects per image your dataset contains. If you have a few large objects per image (lets say 1-3) then you could use for example one of our SimCLR or MoCo models.

 If there are many small objects on the image it becomes more complicated as most self-supervised models assume that two random crops from the same image show the same object. This is no longer the case with small objects, as two crops from the same image could show very different objects. In this case you might want to change the cropping strategy such that the two crops always have some overlap. This approach is well explained in the following paper which also features many results on image segmentation: [Revisiting Contrastive Methods for Unsupervised Learning of Visual Representations
](https://arxiv.org/abs/2106.05967)

There have also been a flurry of new methods developed specifically for object detection and image segmentation on complex images. I put some examples down below:

* [Efficient Visual Pretraining with Contrastive Detection
](https://arxiv.org/abs/2103.10957)
* [Unsupervised Object-Level Representation Learning from Scene Images
](https://arxiv.org/pdf/2106.11952.pdf)
* [Aligning Pretraining for Detection via Object-Level Contrastive Learning
](https://arxiv.org/abs/2106.02637)

Sadly we did not yet have the time to implement those methods.

Could you provide some more details on what exactly you want to do and what type of data you have?

**Comment by miguel-arrf** [comment]
Hi!

@guarin, is there any Segmentation downtask example code available?

Thank you!

**Comment by philippmwirth** [comment]
Hi @miguel-arrf 

Currently we unfortunately don't have any examples for segmentation downstream tasks.

**Comment by miguel-arrf** [comment]
Thank you @philippmwirth !
