### ISSUE TITLE
remove checkpointing from embedding module

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#73]
With the current setup the embedding module `SelfSupervisedEmbedding` automatically creates checkpoints when trained. This also causes problems if checkpoints already exist, basically making it hard to use on its own. I would propose to remove the checkpoint_callback code https://github.com/lightly-ai/lightly/blob/d1b471174f8a37c88432d1592292b3e057940329/lightly/embedding/_base.py#L46 
from the `embedding` module.

I think that should be a rather small change but it could help with usability.

**Comment by philippmwirth** [comment]
We should not remove the code as it is required by the command-line tool. A better approach would be to deactivate checkpointing by default and only activate it when the code is being used by the command line. I will take a look at this.

**Comment by IgorSusmelj** [comment]
Close issue after fix #75
