### ISSUE TITLE
 ActiveLearningAgent: KeyError: 'initial-tag'

### ISSUE THREAD

**Issue by JosianeUwineza** [lightly-ai/lightly#730]
Hello Team, I am new to the Lightly package usage. 
I want to use to apply active learning  for image classification, But trying it as shown in the tutorial I Am getting key error at ActiveLearningAgent :
This the error:

File "/home/josi/anaconda3/envs/ActiveL/lib/python3.8/site-packages/lightly/active_learning/agents/agent.py", line 79, in __init__
    self._query_tag_id = tag_name_id_dict[query_tag_name]
KeyError: 'initial-tag'

Here there is my script:

import os
import csv
from typing import List, Dict, Tuple
import numpy as np
from sklearn.linear_model import LogisticRegression
from lightly.active_learning.agents.agent import ActiveLearningAgent
from lightly.active_learning.config.sampler_config import SamplerConfig
from lightly.active_learning.scorers.classification import ScorerClassification
from lightly.api.api_workflow_client import ApiWorkflowClient
from lightly.openapi_generated.swagger_client import SamplingMethod

class CSVEmbeddingDataset:
    def __init__(self, path_to_embeddings_csv: str):
        with open(path_to_embeddings_csv, 'r') as f:
            data = csv.reader(f)

            rows = list(data)
            header_row = rows[0]
            rows_without_header = rows[1:]

            index_filenames = header_row.index('filenames')
            filenames = [row[index_filenames] for row in rows_without_header]

            index_labels = header_row.index('labels')
            labels = [row[index_labels] for row in rows_without_header]

            embeddings = rows_without_header
            indexes_to_delete = sorted([index_filenames, index_labels], reverse=True)
            for embedding_row in embeddings:
                for index_to_delete in indexes_to_delete:
                    del embedding_row[index_to_delete]

        # create the dataset as a dictionary mapping from the filename to a tuple of the embedding and the label
        self.dataset: Dict[str, Tuple[np.ndarray, int]] = \
            dict([(filename, (np.array(embedding_row, dtype=float), int(label)))
                  for filename, embedding_row, label in zip(filenames, embeddings, labels)])

    def get_features(self, filenames: List[str]) -> np.ndarray:
        features_array = np.array([self.dataset[filename][0] for filename in filenames])
        return features_array

    def get_labels(self, filenames: List[str]) -> np.ndarray:
        labels = np.array([self.dataset[filename][1] for filename in filenames])
        print(labels)
        return labels

#token = os.getenv("LIGHTLY_TOKEN", default="060058fd61697bc640754feb416a1059d04302122e0ffb5a")
token = "060058fd61697bc640754feb416a1059d04302122e0ffb5a"
dataset_id='6228985b0e379e815d391256'
path_to_embeddings_csv = os.getenv("LIGHTLY_EMBEDDINGS_CSV", 
                                   default="./lightly_outputs/2022-03-09/14-43-50/embeddings.csv")
api_workflow_client = ApiWorkflowClient(token, dataset_id)
api_workflow_client.create_dataset(dataset_id)
dataset = CSVEmbeddingDataset(path_to_embeddings_csv=path_to_embeddings_csv)
print(dataset)
classifier = LogisticRegression(max_iter=1000)
agent = ActiveLearningAgent(api_workflow_client=api_workflow_client)  #query_tag_name="initial_40")

#print("Starting the initial sampling")
sampler_config = SamplerConfig(n_samples=400, method=SamplingMethod.CORESET, name='initial-selection')
#agent = ActiveLearningAgent(api_workflow_client)
#agent.query(sampler_config=sampler_config)
print(f"There are {len(agent.labeled_set)} samples in the labeled set.")

labeled_set_features = dataset.get_features(agent.labeled_set)
labeled_set_labels = dataset.get_labels(agent.labeled_set)
classifier.fit(X=labeled_set_features, y=labeled_set_labels)

query_set_features = dataset.get_features(agent.query_set)
predictions = classifier.predict_proba(X=query_set_features)

active_learning_scorer = ScorerClassification(model_output=predictions)

sampler_config = SamplerConfig(n_samples=700, method=SamplingMethod.CORAL, name='al-iteration-1')
agent.query(sampler_config=sampler_config, al_scorer=active_learning_scorer)
print(f"There are {len(agent.labeled_set)} samples in the labeled set.")

labeled_set_features = dataset.get_features(agent.labeled_set)
labeled_set_labels = dataset.get_labels(agent.labeled_set)
classifier.fit(X=labeled_set_features, y=labeled_set_labels)

unlabeled_set_features = dataset.get_features(agent.unlabeled_set)
unlabeled_set_labels = dataset.get_labels(agent.unlabeled_set)
accuracy_on_unlabeled_set = classifier.score(X=unlabeled_set_features, y=unlabeled_set_labels)
print(f"accuracy on unlabeled set: {accuracy_on_unlabeled_set}")

Any Suggestions of how to solve it?

**Comment by MalteEbner** [comment]
Hey @JosianeUwineza , thanks for trying out the tutorial. 
Do I assume correctly that you use this tutorial? https://docs.lightly.ai/tutorials/platform/tutorial_active_learning.html#
The problem is most probably, that you did not upload your dataset yet to the Lightly Platform. Thus it does not include the tag 'initial-tag' You can upload your dataset to the Lightly Platform and browse it there by following the instructions in the first section of the tutorial: https://docs.lightly.ai/tutorials/platform/tutorial_active_learning.html#creation-of-the-dataset-on-the-lightly-platform-with-embeddings

**Comment by JosianeUwineza** [comment]
Hey @MalteEbner, thank you for the comment, I followed the tutorial and finally, it works.
