### ISSUE TITLE
how to use the trained ssl model using lightly to downstream task (BYOL)

### ISSUE THREAD

**Issue by shabbirshuvo** [lightly-ai/lightly#737]
Hi, I am not sure if it is the right place to post this. I am using lightly for my research project. So far I have used it to train my model on the customized dataset using lightly. Thaats a huge help thank you. But now I am not properly understanding how to use my trained byol model to downstream task , for example classification.

Is there any tool available in the framework for this? If not can someone provide me info on how to do this?

Thank you.

**Comment by Atharva-Phatak** [comment]
So SSL is a good pretraining-step for downstream tasks. You used BYOL as a pre-training task which helped your model to learn good representations. Now what you can do is funetune the model on downstream task using [Pytorch-Lightning](https://www.pytorchlightning.ai/) or many plethora PyTorch frameworks available.

For example, we are talking about classification we are running under the assumption that you have labelled dataset, which will be needed since classification is  supervised problem. The only thing you will need to do is load your SSL model weights instead of maybe Imagenet ones. 

Let me know if you have any other questions.

**Comment by MalteEbner** [comment]
We have a tutorial on how to use self-supervised pretaining for an object-detection downstream task. Perhaps you can use that and adapt it to your needs. https://docs.lightly.ai/tutorials/package/tutorial_pretrain_detectron2.html

As a high-level guide:
- have a trainable supervised model for the downstream task (e.g. classification)
- extract the backbone (e.g. resnet50) and create you self-supervised model from it using lightly
- train the self-supervised model using lightly
- put the backbone back into your supervised (e.g. classification) model
- train your supervised model

**Comment by guarin** [comment]
We also have a tutorial that shows how to train a linear classifier on top of your pretrained model: https://docs.lightly.ai/tutorials/package/tutorial_moco_memory_bank.html# 

The classifier is this section: https://docs.lightly.ai/tutorials/package/tutorial_moco_memory_bank.html#create-the-classifier-lightning-module

**Comment by shabbirshuvo** [comment]
thank you all for your kind replies! @guarin sorry again for another silly question. what should I change if I want to use pytorch instead of pl lightning? can you please help me to convert the same tutorial to pytorch trainer instead of pl?

**Comment by Atharva-Phatak** [comment]
@shabbirshuvo here is a tutorial that may help : https://towardsdatascience.com/from-pytorch-to-pytorch-lightning-a-gentle-introduction-b371b7caaf09

**Comment by guarin** [comment]
We have example code on how to train BYOL using pytorch: https://docs.lightly.ai/examples/byol.html


For the classifier something like this should work:

```
import torch

class Classifier(torch.nn.Module):
    def __init__(self, backbone):
        super().__init__()
        # use the pretrained ResNet backbone
        self.backbone = backbone

        # freeze the backbone
        deactivate_requires_grad(backbone)

        # create a linear layer for our downstream classification model
        self.fc = nn.Linear(512, 10)

    def forward(self, x):
        y_hat = self.backbone(x).flatten(start_dim=1)
        y_hat = self.fc(y_hat)
        return y_hat

classifier = Classifier(backbone)
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(classifier.fc.parameters(), lr=30.)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, max_epochs)

for epoch in range(100):
    print('epoch', epoch)

    # train
    classifier.train()
    train_loss = 0
    for x, y, _ in dataloader_train_classifier:
        optimizer.zero_grad()
        y_hat = classifier(x)
        loss = criterion(y_hat, y)
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * len(x)
    train_loss = train_loss / len(dataloader_train_classifier.dataset)
    print('train loss', train_loss)

    # validate
    classifier.eval()
    total_num = 0
    total_correct = 0
    with torch.no_grad():
        for x, y, _ in dataloader_test:
            y_hat = classifier(x)
            y_hat = torch.nn.functional.softmax(y_hat, dim=1)
            # calculate number of correct predictions
            _, predicted = torch.max(y_hat, 1)
            num = predicted.shape[0]
            correct = (predicted == y).float().sum()
            total_num += num
            total_correct += correct
        acc = total_correct / total_num
        print('validation accuracy', acc)
    scheduler.step()
```

I didn't test the code but it should get you started :) It follows the same structure as the moco tutorial: https://docs.lightly.ai/tutorials/package/tutorial_moco_memory_bank.html#

**Comment by shabbirshuvo** [comment]
Thank you everyone for your kind help. It was really helpful and it solved my problem.
