### ISSUE TITLE
Adopting lightly LightlyDataset class for other type of image data (*pt tensor format)

### ISSUE THREAD

**Issue by shabbirshuvo** [lightly-ai/lightly#745]
Hi everyone. I am trying to work with few different kinds of data than standard image formats . I have some medical image data converted to normalized images in *.pt format. Now I want to use LightlyDataset to load these tensor images to create my dataset like the following line of code: 
"dataset = LightlyDataset("path to my tensor images")

is there any tool available in the lighty library to do this? If there is none, can you please tell me how to adapt this class to my situation? 

one thing to mention here, is I have sorted my tensor data similar to imagenet folder structure which is already supported by LightlyDataset class.

Thank you.

**Comment by shabbirshuvo** [comment]
one thing to mention here, is I have sorted my tensor data similar to imagenet folder structure which is already supported by LightlyDataset class.

**Comment by philippmwirth** [comment]
Hi @shabbirshuvo, the `LightlyDataset` currently doesn't support `*.pt` format. What you can do is write your own dataset class which loads the `*.pt` images and then use the `LightlyDataset.from_torch_dataset` function ([link](https://docs.lightly.ai/lightly.data.html#lightly.data.dataset.LightlyDataset.from_torch_dataset)) to wrap it in a `LightlyDataset`. 

Let me know how it goes! I'm happy to help 🙂
