### ISSUE TITLE
How to Use Active Learning on local stored data without uploading the data on lightly web-app

### ISSUE THREAD

**Issue by JosianeUwineza** [lightly-ai/lightly#746]
I would like to ask how to use lightly for  my local data  sampling without uploading the data on  lightly web app.  As it is mentioned in the documentation. 

you can process larger datasets completely on your end without data leaving your infrastructure!!!.

Any tutorial for this?
Ask your account manager from Lightly for the credentials to download the docker container? how to know my account manager from Lightly?

Your support will be much appreciated

**Comment by MalteEbner** [comment]
All features, including Active Learning, that are used in the platform tutorials, work together with the Lightly WebApp:
https://docs.lightly.ai/tutorials/platform.html

We also offer a docker container for running Lightly on-premise. It easily scales to millions of samples and includes on-premise selection and Active Learning. It is documented the `Docker` section: https://docs.lightly.ai/docker/overview.html
If you are interested in trying it out and buying it, contact us under https://www.lightly.ai/contact.
