### ISSUE TITLE
torchvision and torch incompatibility

### ISSUE THREAD

**Issue by NoviceMAn-prog** [lightly-ai/lightly#765]
AttributeError: module 'torchvision.datasets' has no attribute 'VisionDataset'
While using the latest lightly version. Using pervious version throws the same error

**Comment by philippmwirth** [comment]
Hi @NoviceMAn-prog 

Could you please share your `torchvision` version?

**Comment by SonwYang** [comment]
@NoviceMAn-prog Hello, Have you fix this problem?

**Comment by guarin** [comment]
Hi @SonwYang, could you share the error that happens for you? Including lightly version and torchvision version.

**Comment by SonwYang** [comment]
I fixed this problem by myself. Just using the code "from torchvision.datasets import VisionDataset".




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月1日(星期四) 下午3:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lightly-ai/lightly] torchvision and torch incompatibility (Issue #765)





 
Hi @SonwYang, could you share the error that happens for you? Including lightly version and torchvision version.
