### ISSUE TITLE
DCL: Decoupled Contrastive Learning

### ISSUE THREAD

**Issue by guarin** [lightly-ai/lightly#782]
## DCL: Decoupled Contrastive Learning

13.10.2021
https://arxiv.org/abs/2110.06848

Introduces a new contrastive loss function (DCL loss). Compatible with architectures such as SimCLR but trains much faster. Works with small batch sizes.

Estimated effort to implement in Lightly: Very low
* Add DCL Loss

**Comment by IgorSusmelj** [comment]
There is a reference implementation here: https://github.com/raminnakhli/Decoupled-Contrastive-Learning/blob/main/loss/dcl.py

I'd suggest to keep this loss as a separate instead of trying to merge it with the NTX-Ent loss we already have.
