### ISSUE TITLE
Active Learning: Is the sampling method e.g Coreset re-applied after uploading new embedding?

### ISSUE THREAD

**Issue by albertoRodriguezVW** [lightly-ai/lightly#801]
Hi,
first, thanks for the nice package 👍 

I have the following question. Considere I  have a dataset X of unlabeled images and proceed as follows:
1) I compute embeddings with model A  of the dataset X. Moreover, the scores are computed with predictions from model A
2) I compute two subsamplings of the dataset using CORESET and CORAL respectively
3) Now I produce a second set of embeddings with model B of the dataset X
4) In Lighlty "Embeddings" visualisation module, I can see the 2D embeddings of model B and also both selections. My question is: this selection goes back to the selection made based on model A embeddings? Or is CORESET automatically computed for the new embeddings ? I guess the first case occurs since CORAL needs the scores from the predictions which I did not compute with model B.

I just found this a little bit confusing 

Thanks

**Comment by philippmwirth** [comment]
Hi @albertoRodriguezVW 

You are exactly right. The selection is still the one done on embeddings A. It's simply visualized using embeddings B.

Thanks for the feedback! We'll try to make it more clear 🙂
