### ISSUE TITLE
Request to solve issue 

### ISSUE THREAD

**Issue by aqsalab** [lightly-ai/lightly#837]
Hy! 

I'm student of research. I'm interested in your code of lightly and I like it strongly.

I want to use this code in own research era. Related that code I have downloaded all dependencies but one thing can't implement that is lightly.

You used in your code but I can't access through using this command which you have mentioned in readme "pip3 install lightly" please share the copy of version lightly. 

I have some troubles to download the lightly. Please help me and share copy of lightly version that is used in your code.....

**Comment by guarin** [comment]
Hi! 

Could you provide the error that you get when you try to install lightly? This would help us debug your issue :)

**Comment by aqsalab** [comment]
Lightly version 0.0.0 does not support.

**Comment by aqsalab** [comment]
Lightly version 0.0.0 does not support the code .and does not update the
lightly version . please  help to solve this issue in coding

**Comment by guarin** [comment]
Hmm this is weird. How exactly do you install lightly? Could you provide the steps and commands you run? Also, are you installing it in a virtual environment or conda environment?

**Comment by aqsalab** [comment]
I want to install lightly in python 3.6+ with pip3 install lightly  .but
python 3.6+ does not support pip 3 .pip 3 install lightly command not run
in command prompt .I want to try  install in both virtual environment and
conda environment .but in virtual environment the given code of lightly -ai
give me error  of lightly installation   command .and in conda environment,
conda not install in 7th generation .please provide me latest version of
lightly commands  and conda software .I want to latest version of lightly
and conda ..  .

**Comment by guarin** [comment]
Please make sure that you have indeed the correct version of python. Run the following in the terminal and it should show at least python version 3.6:
```
python --version
```

Then you can run:
```
python -m venv lightly-env
source lightly-env/bin/activate
pip install lightly
```
And you should have installed lightly successfully in a new virtual environment.

**Comment by aqsalab** [comment]
Can you help me ?.which  is the main file of this lightly code ?
