### ISSUE TITLE
Help for cuda ...

### ISSUE THREAD

**Issue by ShamsaHasnain** [lightly-ai/lightly#842]
Hy! I want to use this code lightly. How install cuda because when I install cuda error occur "graphic driver not compatible with this version of windows ". 
I have a GPU with same driver. How I solve it plz help me and if you agree to share cuda version So plz help share I want to use it with cuda ....

**Comment by guarin** [comment]
Hi, lightly should be compatible with any recent cuda version as it is built on pytorch. The instructions on how to install pytorch for windows are provided on the pytorch site: https://pytorch.org/get-started/locally/ 

You can verify whether everything is correctly installed by following the steps here: https://pytorch.org/get-started/locally/#windows-verification
