### ISSUE TITLE
Add configuration parameters to CLI documentation

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#85]
The CLI documentation mentions that we have parameters, but there is no list of them. It would be great to provide a lit, so users know what kind of parameters they can set.

**Comment by philippmwirth** [comment]
Do you mean [this list](https://docs.lightly.ai/lightly.cli.html#default-settings)? Maybe we can just link it?

**Comment by IgorSusmelj** [comment]
Yes, exactly. This list + syntax highlighting if possible.

**Comment by philippmwirth** [comment]
Syntax highlighting is done, you can add a link to the list.
