### ISSUE TITLE
Add autocompletion to command-line tool

### ISSUE THREAD

**Issue by philippmwirth** [lightly-ai/lightly#90]
[We can use this for inspiration.](https://github.com/nvm-sh/nvm/blob/master/bash_completion)

**Comment by Nike682631** [comment]
Is this issue available to work on?

**Comment by philippmwirth** [comment]
Yes, this issue is still open and nobody is currently working on it.

**Comment by guarin** [comment]
We have currently don't plan to extend the command line tool.
