### ISSUE TITLE
How to use Swin-Transformer v1/v2 as a backbone?

### ISSUE THREAD

**Issue by sarmientoj24** [lightly-ai/lightly#920]
Is it easy to plug-in? And which SSL models can accomodate it out of the box?

**Comment by philippmwirth** [comment]
Hi @sarmientoj24, since all our SSL models work with an abstraction for the backbone it should be rather easy to plug-in the Swin-Transformers. I only see difficulties for MAE and MSN. I will take a look to see how much effort it is 👍
