### ISSUE TITLE
train any types of backbone for masked based model 

### ISSUE THREAD

**Issue by ramdhan1989** [lightly-ai/lightly#935]
Hi, is it possible to use non transformer backbone in masked based model such as MAE or MSN? actually, I would like to train backbone using MAE or MSN for object detection using detectron2. I only found an example using contrastive based model. 

thank you

**Comment by guarin** [comment]
Hi @ramdhan1989

MAE and MSN do not directly work with convnet backbones. You could maybe try "masking" image patches by setting the rgb values in the masked patches to 0 and then passing the image through the backbone. But I have not seen it yet in the literature.

But you might be interested in [SimMIM](https://arxiv.org/abs/2111.09886) which is sadly not yet implemented in Lightly but allows training with resnets (see Section E in the appendix). We even have discussion about it in one of our issues: https://github.com/lightly-ai/lightly/issues/780 I think it should be possible to implement with Lightly. Let me know if you are interested in trying it out :)

**Comment by ramdhan1989** [comment]
Ok thanks a lot for your suggestion @guarin
