### ISSUE TITLE
Add multiprototype-heads for SWAV

### ISSUE THREAD

**Issue by Atharva-Phatak** [lightly-ai/lightly#944]
I took a look at the implementation of SWAV lightly and the one in FAIR's repo (https://github.com/facebookresearch/swav/blob/main/src/resnet50.py). Lightly uses a single ```nn. Linear``` for prototypes but FAIR implementation has multiple prototype heads ? Any reason why lightly uses a single linear layer?

If not can we make it a Multi prototype head with multiple ```nn. Linear``` ? 

If so I can make a quick PR for these changes.

**Comment by guarin** [comment]
Hi, yes you are completely right, we only added single prototype head. We added the single head because this is the default setting in SwAV. 

Adding a multiprototype head seems like a perfect addition to Lightly and a PR would be more than welcome :)

**Comment by Atharva-Phatak** [comment]
Sure I will create a PR asap :)
