### ISSUE TITLE
SSL Online Evaluator Callback with Custom Data (i.e., different than pre-training data)

### ISSUE THREAD

**Issue by aqibsaeed** [lightly-ai/lightly#977]
Hi,

Is it possible to use online evaluation of SSL encoder with a linear classifier to run on different data then the one being used for pre-training?

**Comment by guarin** [comment]
Hi @aqibsaeed,

Yes, it is common to evaluate a model on a different dataset than the dataset that was used for pretraining. In this case, you usually also have to fine-tune (train the classifier) on the dataset used for evaluation.
