### ISSUE TITLE
Make transform settable in Lightly Dataset 

### ISSUE THREAD

**Issue by shruti-shyam** [lightly-ai/lightly#98]
Currently if one has created a Lightly Dataset and wants to apply transforms at a later stage, we have to do it as follows:
```
dataset = data.LightlyDataset(root="./", name='CIFAR10', download=True)
...
use dataset to train SimCLR model for example
...
test_transforms = torchvision.transforms.ToTensor()
dataset.dataset.transform = test_transforms
```

We should extend the Dataset wrapper to directly support transforms.

**Comment by MalteEbner** [comment]
The same problem occurs with `LightlyDataset.from_torch_dataset(dataset, transform, index_to_filename)`: Even if a transform is passed it is never set, as the main init only sets a transform if the dataset is not None.

**Comment by philippmwirth** [comment]
> 
> 
> The same problem occurs with `LightlyDataset.from_torch_dataset(dataset, transform, index_to_filename)`: Even if a transform is passed it is never set, as the main init only sets a transform if the dataset is not None.

Can you not simply set the transform of the dataset you pass?

**Comment by philippmwirth** [comment]
One fix that comes to mind is
1. setting the transform correctly in the constructor
2. having properties for all the attributes of the torchvision datasets (including transform), e.g.
```python
class LightlyDataset(...):

    @property
    def transform(self):
        return self.dataset.transform

    @transform.setter
    def transform(self, t):
        self.dataset.transform = t
